import type { ReactNode } from 'react';
import type { CurrencyCode } from '@/lib/units-preferences';
import type { UnitSystem } from '@/lib/construction';

type Extra=Record<string,string>; export type AdvancedLine={label:string;value:string};
const num=(v:string|number|undefined,f=0)=>{const x=Number(v);return Number.isFinite(x)&&x>=0?x:f};
const money=(v:number,c:CurrencyCode)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:2}).format(v);
const Box=({children}:{children:ReactNode})=><div className="construction-advanced-fields"><div className="eyebrow">ADVANCED ORDER OPTIONS</div>{children}</div>;
const F=({label,unit,value,onChange,step='0.01'}:{label:string;unit?:string;value:string;onChange:(v:string)=>void;step?:string})=><label className="construction-field"><span>{label}{unit&&<small>{unit}</small>}</span><input type="number" min="0" step={step} value={value} onChange={e=>onChange(e.target.value)}/></label>;
export function ConstructionAdvancedOptions({slug,unit,extra,setExtra,currency}:{slug:string;unit:UnitSystem;extra:Extra;setExtra:(v:Extra)=>void;currency:CurrencyCode}){const set=(k:string,v:string)=>setExtra({...extra,[k]:v});
if(slug==='gravel')return <Box><p className="advanced-mode-explainer">Turn the gravel requirement into a supplier-ready order using load increments, minimum order and delivery charge.</p><div className="construction-fields"><F label="Supplier load increment" unit={unit==='imperial'?'tons':'tonnes'} value={extra.loadIncrement??'0.5'} onChange={v=>set('loadIncrement',v)}/><F label="Minimum order" unit={unit==='imperial'?'tons':'tonnes'} value={extra.minimumOrder??'0'} onChange={v=>set('minimumOrder',v)}/><F label="Delivery charge" unit={currency} value={extra.delivery??'0'} onChange={v=>set('delivery',v)}/></div></Box>;
if(slug==='mulch')return <Box><p className="advanced-mode-explainer">Convert the calculated mulch into a supplier-rounded bulk delivery quantity.</p><div className="construction-fields"><F label="Bulk delivery increment" unit={unit==='imperial'?'yd³':'m³'} value={extra.bulkIncrement??(unit==='imperial'?'0.5':'0.25')} onChange={v=>set('bulkIncrement',v)}/><F label="Minimum bulk order" unit={unit==='imperial'?'yd³':'m³'} value={extra.minimumBulk??'0'} onChange={v=>set('minimumBulk',v)}/></div></Box>;
if(slug==='roof-pitch')return <Box><p className="advanced-mode-explainer">Apply the slope multiplier to a horizontal roof footprint to estimate sloped surface area.</p><div className="construction-fields"><F label="Horizontal roof area" unit={unit==='imperial'?'ft²':'m²'} value={extra.planArea??'1000'} onChange={v=>set('planArea',v)}/></div></Box>;
if(slug==='roofing-material')return <Box><p className="advanced-mode-explainer">Use the exact product packaging and add separate ridge or starter bundles.</p><div className="construction-fields"><F label="Bundles per roofing square" value={extra.bundlesPerSquare??'3'} onChange={v=>set('bundlesPerSquare',v)}/><F label="Extra ridge / starter bundles" value={extra.extraBundles??'0'} onChange={v=>set('extraBundles',v)} step="1"/></div></Box>;
if(slug==='stair')return <Box><p className="advanced-mode-explainer">Check the stair against your chosen maximum riser, minimum tread and available horizontal space. This is a planning check, not a building-code approval.</p><div className="construction-fields"><F label="Available horizontal run" unit={unit==='imperial'?'in':'cm'} value={extra.availableRun??(unit==='imperial'?'144':'366')} onChange={v=>set('availableRun',v)}/><F label="Minimum headroom" unit={unit==='imperial'?'in':'cm'} value={extra.headroom??(unit==='imperial'?'80':'203')} onChange={v=>set('headroom',v)}/></div></Box>;
if(slug==='board-foot')return <Box><p className="advanced-mode-explainer">Add cutting/defect waste and a supplier price per board foot to turn lumber volume into a purchase estimate.</p><div className="construction-fields"><F label="Waste / defect allowance" unit="%" value={extra.lumberWaste??'10'} onChange={v=>set('lumberWaste',v)}/><F label="Price per board foot" unit={currency} value={extra.pricePerBoardFoot??'0'} onChange={v=>set('pricePerBoardFoot',v)}/></div></Box>;
if(slug==='deck-material')return <Box><p className="advanced-mode-explainer">Add spare boards and supplier pack size so the field-board estimate becomes a whole-pack purchase quantity.</p><div className="construction-fields"><F label="Extra spare boards" value={extra.spareBoards??'2'} onChange={v=>set('spareBoards',v)} step="1"/><F label="Boards per pack" value={extra.boardsPerPack??'1'} onChange={v=>set('boardsPerPack',v)} step="1"/></div></Box>;
if(slug==='fence-material')return <Box><p className="advanced-mode-explainer">Add spare posts, pickets and rails for breakage, corners or future repairs.</p><div className="construction-fields"><F label="Extra posts" value={extra.extraPosts??'1'} onChange={v=>set('extraPosts',v)} step="1"/><F label="Extra pickets" value={extra.extraPickets??'5'} onChange={v=>set('extraPickets',v)} step="1"/><F label="Extra rails" value={extra.extraRails??'2'} onChange={v=>set('extraRails',v)} step="1"/></div></Box>;
if(slug==='drywall')return <Box><p className="advanced-mode-explainer">Convert the sheet estimate into whole packs and keep additional spare sheets for damage or future repair.</p><div className="construction-fields"><F label="Sheets per pack" value={extra.sheetsPerPack??'1'} onChange={v=>set('sheetsPerPack',v)} step="1"/><F label="Extra spare sheets" value={extra.spareSheets??'1'} onChange={v=>set('spareSheets',v)} step="1"/></div></Box>;
if(slug==='brick')return <Box><p className="advanced-mode-explainer">Add a spare brick reserve and convert the order to complete supplier packs or pallets.</p><div className="construction-fields"><F label="Extra spare bricks" value={extra.spareBricks??'25'} onChange={v=>set('spareBricks',v)} step="1"/><F label="Bricks per pack / pallet" value={extra.bricksPerPack??'500'} onChange={v=>set('bricksPerPack',v)} step="1"/></div></Box>;
return null}
export function constructionAdvancedLines(slug:string,unit:UnitSystem,engine:Record<string,string|number>,raw:number,extra:Extra,currency:CurrencyCode):AdvancedLine[]{
if(slug==='gravel'){const weight=raw,price=num(engine.price),inc=Math.max(.01,num(extra.loadIncrement,.5)),minimum=num(extra.minimumOrder),order=Math.max(minimum,Math.ceil(weight/inc)*inc),delivery=num(extra.delivery);return[{label:'Calculated material weight',value:`${weight.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'tons':'tonnes'}`},{label:'Supplier-rounded order',value:`${order.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'tons':'tonnes'}`},{label:'Material cost',value:money(order*price,currency)},{label:'Estimated total with delivery',value:money(order*price+delivery,currency)}]}
if(slug==='mulch'){const length=num(engine.length),width=num(engine.width),depth=num(engine.depth),waste=1+num(engine.waste)/100;const m3=(unit==='imperial'?length*.3048:length)*(unit==='imperial'?width*.3048:width)*(unit==='imperial'?depth*.0254:depth/100)*waste;const volume=unit==='imperial'?m3*1.30795062:m3,inc=Math.max(.01,num(extra.bulkIncrement,unit==='imperial'?.5:.25)),minimum=num(extra.minimumBulk),bulk=Math.max(minimum,Math.ceil(volume/inc)*inc);return[{label:'Calculated bulk volume',value:`${volume.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'yd³':'m³'}`},{label:'Supplier-rounded bulk order',value:`${bulk.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'yd³':'m³'}`}]}
if(slug==='roof-pitch'){const rise=num(engine.rise),run=num(engine.run);if(run<=0)return[];const mult=Math.sqrt(1+(rise/run)**2),plan=num(extra.planArea,1000);return[{label:'Slope multiplier',value:mult.toFixed(3)},{label:'Horizontal plan area',value:`${plan.toLocaleString()} ${unit==='imperial'?'ft²':'m²'}`},{label:'Estimated sloped area',value:`${(plan*mult).toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'ft²':'m²'}`}]}
if(slug==='roofing-material'){const bundlesPer=Math.max(.01,num(extra.bundlesPerSquare,3)),extras=Math.ceil(num(extra.extraBundles)),squares=raw,bundles=Math.ceil(squares*bundlesPer)+extras;return[{label:'Roofing squares',value:squares.toLocaleString(undefined,{maximumFractionDigits:2})},{label:'Bundles per square',value:String(bundlesPer)},{label:'Main bundles',value:String(Math.ceil(squares*bundlesPer))},{label:'Total bundles with extras',value:String(bundles)}]}
if(slug==='stair'){const total=unit==='imperial'?num(engine.totalRise):num(engine.totalRise),max=Math.max(.01,num(engine.maxRiser)),tread=num(engine.minTread),risers=Math.ceil(total/max),treads=Math.max(1,risers-1),required=treads*tread,available=num(extra.availableRun,unit==='imperial'?144:366);return[{label:'Riser count',value:String(risers)},{label:'Required horizontal run',value:`${required.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'in':'cm'}`},{label:'Available horizontal run',value:`${available.toLocaleString()} ${unit==='imperial'?'in':'cm'}`},{label:'Run check',value:available>=required?'Fits entered space':'More horizontal space required'},{label:'Entered minimum headroom',value:`${num(extra.headroom,unit==='imperial'?80:203)} ${unit==='imperial'?'in':'cm'}`}];}
if(slug==='board-foot'){const waste=num(extra.lumberWaste,10),purchase=raw*(1+waste/100),price=num(extra.pricePerBoardFoot);return[{label:'Calculated board feet',value:raw.toLocaleString(undefined,{maximumFractionDigits:2})},{label:'Purchase board feet with waste',value:purchase.toLocaleString(undefined,{maximumFractionDigits:2})},{label:'Waste / defect allowance',value:`${waste}%`},...(price>0?[{label:'Estimated lumber cost',value:money(purchase*price,currency)}]:[])];}
if(slug==='deck-material'){const spares=Math.ceil(num(extra.spareBoards,2)),per=Math.max(1,Math.floor(num(extra.boardsPerPack,1))),needed=Math.ceil(raw)+spares,packs=Math.ceil(needed/per);return[{label:'Base board estimate',value:String(Math.ceil(raw))},{label:'Boards including spares',value:String(needed)},{label:'Whole packs to buy',value:String(packs)},{label:'Boards supplied',value:String(packs*per)}];}
if(slug==='fence-material'){const length=unit==='imperial'?num(engine.length)*.3048:num(engine.length),spacing=unit==='imperial'?num(engine.postSpacing)*.3048:num(engine.postSpacing),picket=unit==='imperial'?num(engine.picketWidth)*.0254:num(engine.picketWidth)/1000,gap=unit==='imperial'?num(engine.gap)*.0254:num(engine.gap)/1000,sections=Math.ceil(length/spacing),posts=sections+1+2*num(engine.gates),pickets=Math.ceil(length/(picket+gap)),rails=sections*num(engine.rails);return[{label:'Posts including spares',value:String(posts+Math.ceil(num(extra.extraPosts,1)))},{label:'Pickets including spares',value:String(pickets+Math.ceil(num(extra.extraPickets,5)))},{label:'Rails including spares',value:String(rails+Math.ceil(num(extra.extraRails,2)))}];}
if(slug==='drywall'){const spares=Math.ceil(num(extra.spareSheets,1)),per=Math.max(1,Math.floor(num(extra.sheetsPerPack,1))),needed=Math.ceil(raw)+spares,packs=Math.ceil(needed/per);return[{label:'Calculated sheets',value:String(Math.ceil(raw))},{label:'Sheets including spares',value:String(needed)},{label:'Whole packs to buy',value:String(packs)},{label:'Sheets supplied',value:String(packs*per)}];}
if(slug==='brick'){const spares=Math.ceil(num(extra.spareBricks,25)),per=Math.max(1,Math.floor(num(extra.bricksPerPack,500))),needed=Math.ceil(raw)+spares,packs=Math.ceil(needed/per);return[{label:'Calculated bricks',value:String(Math.ceil(raw))},{label:'Bricks including spares',value:String(needed)},{label:'Whole packs / pallets',value:String(packs)},{label:'Bricks supplied',value:String(packs*per)}];}
return[]}
