import type { CurrencyCode } from '@/lib/units-preferences';
import type { UnitSystem } from '@/lib/construction';

type Extra = Record<string,string>;
export type AdvancedLine={label:string;value:string};
const num=(v:string|number|undefined,f=0)=>{const n=Number(v);return Number.isFinite(n)&&n>=0?n:f};
const money=(value:number,currency:CurrencyCode)=>new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:2}).format(value);
const Box=({children}:{children:React.ReactNode})=><div className="construction-advanced-fields"><div className="eyebrow">ADVANCED ORDER OPTIONS</div>{children}</div>;
const F=({label,unit,value,onChange,step='0.01'}:{label:string;unit?:string;value:string;onChange:(v:string)=>void;step?:string})=><label className="construction-field"><span>{label}{unit&&<small>{unit}</small>}</span><input type="number" min="0" step={step} value={value} onChange={e=>onChange(e.target.value)}/></label>;
export function ConstructionAdvancedOptions({slug,unit,extra,setExtra,currency}:{slug:string;unit:UnitSystem;extra:Extra;setExtra:(v:Extra)=>void;currency:CurrencyCode}){const set=(k:string,v:string)=>setExtra({...extra,[k]:v});if(slug==='gravel')return <Box><p className="advanced-mode-explainer">Turn the calculated gravel requirement into a supplier-ready order using load increments, minimum order and delivery charge.</p><div className="construction-fields"><F label="Supplier load increment" unit={unit==='imperial'?'tons':'tonnes'} value={extra.loadIncrement??'0.5'} onChange={v=>set('loadIncrement',v)}/><F label="Minimum order" unit={unit==='imperial'?'tons':'tonnes'} value={extra.minimumOrder??'0'} onChange={v=>set('minimumOrder',v)}/><F label="Delivery charge" unit={currency} value={extra.delivery??'0'} onChange={v=>set('delivery',v)}/></div></Box>;
if(slug==='mulch')return <Box><p className="advanced-mode-explainer">Compare bag purchasing with bulk delivery and include a supplier minimum bulk quantity.</p><div className="construction-fields"><F label="Bulk delivery increment" unit={unit==='imperial'?'yd³':'m³'} value={extra.bulkIncrement??(unit==='imperial'?'0.5':'0.25')} onChange={v=>set('bulkIncrement',v)}/><F label="Minimum bulk order" unit={unit==='imperial'?'yd³':'m³'} value={extra.minimumBulk??'0'} onChange={v=>set('minimumBulk',v)}/></div></Box>;
if(slug==='roof-pitch')return <Box><p className="advanced-mode-explainer">Apply the calculated slope multiplier to a horizontal roof footprint to estimate sloped surface area.</p><div className="construction-fields"><F label="Horizontal roof area" unit={unit==='imperial'?'ft²':'m²'} value={extra.planArea??'1000'} onChange={v=>set('planArea',v)}/></div></Box>;
if(slug==='roofing-material')return <Box><p className="advanced-mode-explainer">Use the exact product packaging instead of assuming three bundles per roofing square.</p><div className="construction-fields"><F label="Bundles per roofing square" value={extra.bundlesPerSquare??'3'} onChange={v=>set('bundlesPerSquare',v)}/><F label="Extra ridge / starter bundles" value={extra.extraBundles??'0'} onChange={v=>set('extraBundles',v)} step="1"/></div></Box>;
return null}
export function constructionAdvancedLines(slug:string,unit:UnitSystem,engine:Record<string,string|number>,raw:number,extra:Extra,currency:CurrencyCode):AdvancedLine[]{if(slug==='gravel'){const density=num(engine.density),price=num(engine.price),volume=raw;const weight=unit==='imperial'?volume*density:(volume*density)/1000;const inc=Math.max(.01,num(extra.loadIncrement,.5)),minimum=num(extra.minimumOrder),order=Math.max(minimum,Math.ceil(weight/inc)*inc),delivery=num(extra.delivery);return[{label:'Calculated material weight',value:`${weight.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'tons':'tonnes'}`},{label:'Supplier-rounded order',value:`${order.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'tons':'tonnes'}`},{label:'Material cost',value:money(order*price,currency)},{label:'Estimated total with delivery',value:money(order*price+delivery,currency)}]}
if(slug==='mulch'){const inc=Math.max(.01,num(extra.bulkIncrement,unit==='imperial'?.5:.25)),minimum=num(extra.minimumBulk),bulk=Math.max(minimum,Math.ceil(raw/inc)*inc);return[{label:'Calculated bulk volume',value:`${raw.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'yd³':'m³'}`},{label:'Supplier-rounded bulk order',value:`${bulk.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'yd³':'m³'}`}]}
if(slug==='roof-pitch'){const rise=num(engine.rise),run=num(engine.run);if(run<=0)return[];const ratio=rise/run,mult=Math.sqrt(1+ratio*ratio),plan=num(extra.planArea,1000);return[{label:'Slope multiplier',value:mult.toFixed(3)},{label:'Horizontal plan area',value:`${plan.toLocaleString()} ${unit==='imperial'?'ft²':'m²'}`},{label:'Estimated sloped area',value:`${(plan*mult).toLocaleString(undefined,{maximumFractionDigits:2})} ${unit==='imperial'?'ft²':'m²'}`}]}
if(slug==='roofing-material'){const bundlesPer=Math.max(.01,num(extra.bundlesPerSquare,3)),extraBundles=Math.ceil(num(extra.extraBundles)),area=raw;const ft2=unit==='imperial'?area:area*10.7639104167,squares=ft2/100,bundles=Math.ceil(squares*bundlesPer)+extraBundles;return[{label:'Roofing squares',value:squares.toLocaleString(undefined,{maximumFractionDigits:2})},{label:'Bundles per square',value:String(bundlesPer)},{label:'Main + extra bundles to buy',value:String(bundles)}]}
return[]}
