import { useMemo, useState, type ReactNode } from 'react';
import '@/styles/advanced-calculator-pages.css';
import { Seo } from '@/pages/AppPages';
import { Shell } from '@/components/FigureNestShell';
import { Link } from '@/components/PublicLink';
import { CalculatorModeSwitch } from '@/components/calculators/CalculatorDecisionExpansion';
import { calculateAge } from '@/lib/age-calculator';
import { workDateCalculatorContent } from '@/lib/work-date-calculators';

type Slug = 'age' | 'working-days';
const DAY = 86400000;
const date = (s:string) => { const d=new Date(`${s}T00:00:00Z`); return Number.isNaN(d.getTime())?null:d; };

export function AdvancedWorkDateCalculatorPage({slug}:{slug:Slug}) { return slug==='age' ? <Age /> : <WorkingDays />; }
function Frame({slug,advanced,setAdvanced,children,result,breakdown}:{slug:Slug;advanced:boolean;setAdvanced:(v:boolean)=>void;children:ReactNode;result:string;breakdown:{label:string;value:string}[]}) { const c=workDateCalculatorContent[slug]; return <Shell><Seo path={`/calculators/date-time/${slug}`} /><div className="advanced-calc-page"><nav aria-label="Breadcrumb" className="mono"><Link href="/">Home</Link> / <Link href="/category/date-time">Date &amp; Time</Link> / {c.title}</nav><div className="advanced-calc-layout"><div className="advanced-calc-copy"><div className="eyebrow"><span className="eyebrow-dot"/> DATE &amp; TIME</div><h1>{c.titleLines[0]}<br/>{c.titleLines[1]}<span>.</span></h1><p>{c.description}</p><div className="calc-updated mono">UPDATED SEPTEMBER 2026 · {c.methodLabel}</div></div><section className="advanced-calculator-card"><div className="advanced-calc-head"><span className="mono">{c.title.toUpperCase()} — CALCULATE</span><div className="live-dot"><i/> LIVE RESULT</div></div><CalculatorModeSwitch advanced={advanced} onChange={setAdvanced}/><div className="advanced-fields">{children}</div><div className="advanced-result" role="status" aria-live="polite"><span className="mono">{c.resultLabel}</span><strong>{result}</strong><p>{c.resultSummary}</p></div><div className="advanced-breakdown"><span className="mono">BREAKDOWN</span>{breakdown.map(x=><div key={x.label}><span>{x.label}</span><strong>{x.value}</strong></div>)}</div></section></div><Content slug={slug}/></div></Shell>; }
function Field({label,type='date',value,onChange}:{label:string;type?:string;value:string;onChange:(v:string)=>void}) {return <label className="advanced-field"><span>{label}</span><div><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></div></label>}
function Age(){const [advanced,setAdvanced]=useState(false);const [birth,setBirth]=useState('1990-06-14');const [asOf,setAsOf]=useState(new Date().toISOString().slice(0,10));const r=useMemo(()=>{const age=calculateAge(birth,asOf);if(!age.ok)return {p:age.error,d:[]};return {p:age.primary,d:[{label:'Total months (completed)',value:String(age.totalMonths)},{label:'Total weeks',value:age.totalWeeks.toLocaleString()},{label:'Total days',value:age.totalDays.toLocaleString()},...(advanced?[{label:'Born on',value:age.bornOn},{label:'Next birthday',value:age.nextBirthday},{label:'Days until next birthday',value:String(age.daysUntilNextBirthday)}]:[])]}},[birth,asOf,advanced]);return <Frame slug="age" advanced={advanced} setAdvanced={setAdvanced} result={r.p} breakdown={r.d}><Field label="Date of birth" value={birth} onChange={setBirth}/><Field label="Age as of" value={asOf} onChange={setAsOf}/></Frame>}
function WorkingDays(){const [advanced,setAdvanced]=useState(false);const [start,setStart]=useState('2026-09-01');const [end,setEnd]=useState('2026-09-30');const [holidays,setHolidays]=useState('');const [workdays,setWorkdays]=useState('1,2,3,4,5');const r=useMemo(()=>{let a=date(start),b=date(end);if(!a||!b)return {p:'Enter valid dates',d:[]};if(a>b)[a,b]=[b,a];const active=new Set(workdays.split(',').map(Number));const excluded=new Set(holidays.split(/[,\s]+/).filter(Boolean));let working=0,weekend=0,holiday=0,total=0;for(let d=new Date(a);d<=b;d=new Date(d.getTime()+DAY)){total++;const iso=d.toISOString().slice(0,10);if(!active.has(d.getUTCDay()))weekend++;else if(advanced&&excluded.has(iso))holiday++;else working++;}return {p:`${working.toLocaleString()} working days`,d:[{label:'Calendar days (inclusive)',value:String(total)},{label:'Non-working schedule days',value:String(weekend)},...(advanced?[{label:'Excluded dates',value:String(holiday)}]:[])]}},[start,end,holidays,workdays,advanced]);return <Frame slug="working-days" advanced={advanced} setAdvanced={setAdvanced} result={r.p} breakdown={r.d}><Field label="Start date" value={start} onChange={setStart}/><Field label="End date" value={end} onChange={setEnd}/>{advanced&&<><label className="advanced-field"><span>Working weekdays</span><div><select value={workdays} onChange={e=>setWorkdays(e.target.value)}><option value="1,2,3,4,5">Monday–Friday</option><option value="0,1,2,3,4">Sunday–Thursday</option><option value="1,2,3,4,5,6">Monday–Saturday</option><option value="0,1,2,3,4,5,6">Every day</option></select></div></label><Field label="Excluded dates (YYYY-MM-DD, separated by commas)" type="text" value={holidays} onChange={setHolidays}/></>}</Frame>}
function Content({slug}:{slug:Slug}){const c=workDateCalculatorContent[slug];return <div className="advanced-content-grid"><article className="advanced-content"><section><div className="eyebrow">WHEN THIS TOOL HELPS</div><h2>A practical date calculation.</h2><p>{c.whenUseful}</p><ul>{c.usefulFor.map(x=><li key={x}>{x}</li>)}</ul></section><section><div className="eyebrow">HOW IT WORKS</div><h2>Calculation method.</h2><code>{c.formula}</code><p>{c.formulaExplanation}</p></section><section><div className="eyebrow">STEP BY STEP</div><h2>How to use it.</h2><ol>{c.instructions.map(x=><li key={x}>{x}</li>)}</ol></section><section><div className="eyebrow">EXAMPLES</div><h2>Worked examples.</h2>{c.examples.map(x=><div key={x.title}><h3>{x.title}</h3><p>{x.inputs}</p><p><strong>Result:</strong> {x.result}</p><p>{x.interpretation}</p></div>)}</section><section><div className="eyebrow">ASSUMPTIONS</div><h2>What the calculation assumes.</h2><ul>{c.assumptions.map(x=><li key={x}>{x}</li>)}</ul></section><section><div className="eyebrow">COMMON MISTAKES</div><h2>Checks before relying on the result.</h2><ul>{c.commonMistakes.map(x=><li key={x}>{x}</li>)}</ul></section><section><div className="eyebrow">EDGE CASES</div><h2>Special cases.</h2>{c.edgeCases.map(x=><div key={x.title}><h3>{x.title}</h3><p>{x.explanation}</p></div>)}</section><section><div className="eyebrow">LIMITATIONS</div><h2>What to keep in mind.</h2><p>{c.limitations}</p></section><section className="advanced-faq"><div className="eyebrow">FAQ</div><h2>Questions people ask.</h2>{c.faqs.map(x=><details key={x.question}><summary>{x.question}</summary><p>{x.answer}</p></details>)}</section><section><div className="eyebrow">RELATED TOOLS</div><h2>Continue your calculation.</h2>{c.relatedTools.map(x=><p key={x.slug}><Link href={x.slug==='percentage-increase-decrease'?'/calculators/math/percentage-increase-decrease':x.slug==='salary'?'/calculators/salary-work/salary':`/calculators/date-time/${x.slug}`}>{x.linkLabel}</Link> — {x.context}</p>)}</section></article></div>}
