import { useMemo, useState, type ReactNode } from 'react';
import '@/styles/advanced-calculator-pages.css';
import { Shell } from '@/components/FigureNestShell';
import { Seo } from '@/pages/AppPages';
import { Link } from '@/components/PublicLink';
import { CurrencySelector } from '@/components/UnitsPreferencesSelectors';
import { CalculatorModeSwitch } from '@/components/calculators/CalculatorDecisionExpansion';
import { formatCurrency, useUnitsPreferences } from '@/lib/units-preferences';

type Slug = 'hours' | 'time-duration' | 'age' | 'working-days';
type Shift = { start:string; end:string; breakMinutes:string };
const MS_DAY=86400000;
const pad=(n:number)=>String(n).padStart(2,'0');
const parseTime=(v:string)=>{const m=/^(\d{2}):(\d{2})$/.exec(v);if(!m)return NaN;const h=+m[1],min=+m[2];return h<24&&min<60?h*60+min:NaN};
const shiftMinutes=(s:Shift)=>{const a=parseTime(s.start),b=parseTime(s.end),br=Number(s.breakMinutes);if(!Number.isFinite(a)||!Number.isFinite(b)||!Number.isFinite(br)||br<0)return NaN;let elapsed=b-a;if(elapsed<0)elapsed+=1440;return elapsed-br};
const dateUTC=(v:string)=>{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v);if(!m)return undefined;const y=+m[1],mo=+m[2],d=+m[3],x=new Date(Date.UTC(y,mo-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===mo-1&&x.getUTCDate()===d?x:undefined};
const isLeapYear=(y:number)=>y%4===0&&(y%100!==0||y%400===0);
const birthdayInYear=(birth:Date,y:number)=>birth.getUTCMonth()===1&&birth.getUTCDate()===29&&!isLeapYear(y)?new Date(Date.UTC(y,2,1)):new Date(Date.UTC(y,birth.getUTCMonth(),birth.getUTCDate()));
const today=new Date().toISOString().slice(0,10);
const copy:Record<Slug,{title:string;description:string;formula:string;faq:[string,string][]}>={
 hours:{title:'Hours Calculator',description:'Calculate paid time across one or multiple shifts, subtract unpaid breaks, convert to decimal hours, and optionally estimate gross pay.',formula:'paid time = elapsed shift time − unpaid breaks',faq:[['Can a shift cross midnight?','Yes. When clock-out is earlier than clock-in, the calculator treats the shift as ending the following day.'],['What are decimal hours?','Decimal hours express minutes as a fraction of an hour. For example, 7 hours 30 minutes is 7.5 hours.'],['Does it calculate pay?','Advanced mode can estimate gross pay using the hourly rate you enter.'],['Are breaks automatically deducted?','Only the unpaid break minutes you enter are deducted.'],['Does this determine overtime?','No. Overtime eligibility depends on employment terms and applicable rules; use the Overtime Calculator for an entered overtime rate.']]},
 'time-duration':{title:'Time Duration Calculator',description:'Measure elapsed time between date-and-time entries, with optional break deduction and payroll-friendly decimal hours.',formula:'duration = end date/time − start date/time − optional break',faq:[['Can it span multiple days?','Yes. Use the full start and end date-and-time fields.'],['Does it show decimal hours?','Yes. Advanced mode shows decimal hours as well as days, hours and minutes.'],['Can I deduct a break?','Yes in Advanced mode. Enter unpaid break minutes.'],['Does daylight saving affect the result?','The calculator uses the local date-and-time values entered and does not infer a time zone or daylight-saving transition.'],['Can I use this for payroll?','It is useful for checking elapsed time, but employer rounding and payroll rules should be applied separately.']]},
 age:{title:'Age Calculator',description:'Calculate exact age on any date and see age in total months, weeks and days plus the next birthday countdown.',formula:'exact age = as-of date − birth date using calendar years, months and days',faq:[['How is exact age calculated?','Calendar years, months and days are counted rather than dividing total days by 365.'],['Can I calculate age on a past date?','Yes, provided the as-of date is on or after the birth date.'],['Does it handle leap years?','Yes. Gregorian calendar dates are used.'],['What does total months mean?','Advanced mode shows completed calendar months plus the remaining partial month separately in the exact-age result.'],['How are February 29 birthdays handled?','For the birthday countdown, February 29 is used in leap years and March 1 is used as the next valid anniversary date in non-leap years.']]},
 'working-days':{title:'Working Days Calculator',description:'Count working days between two dates with configurable weekend presets, manually excluded dates, and an inclusive or exclusive end date.',formula:'working days = included calendar dates − selected non-working weekdays − manually excluded active dates',faq:[['Are both dates included?','Basic mode includes both dates. Advanced mode lets you exclude the end date.'],['Can I change the weekend?','Yes. Advanced mode supports Saturday/Sunday, Friday/Saturday, Sunday only, or no weekend exclusion.'],['Can I exclude specific dates?','Yes. Enter excluded dates separated by commas using YYYY-MM-DD format.'],['Are public holidays added automatically?','No. Holiday calendars vary by country, region and employer, so only dates you enter manually are excluded.'],['What if an excluded date falls on a non-working weekday?','It is already excluded by the selected schedule and does not reduce the working-day count twice.']]}
};
export function WorkTimeExpansionPage({slug}:{slug:Slug}){
 const c=copy[slug], [advanced,setAdvanced]=useState(false), prefs=useUnitsPreferences(), currency=prefs.forCalculator(slug).currency;
 const [shifts,setShifts]=useState<Shift[]>([{start:'09:00',end:'17:30',breakMinutes:'30'}]),[rate,setRate]=useState('20');
 const [startDT,setStartDT]=useState('2026-09-07T09:00'),[endDT,setEndDT]=useState('2026-09-07T17:30'),[durationBreak,setDurationBreak]=useState('30');
 const [birth,setBirth]=useState('1990-06-14'),[asOf,setAsOf]=useState(today);
 const [workStart,setWorkStart]=useState('2026-09-01'),[workEnd,setWorkEnd]=useState('2026-09-30'),[weekend,setWeekend]=useState('sat-sun'),[holidays,setHolidays]=useState(''),[includeEnd,setIncludeEnd]=useState(true);
 const result=useMemo(()=>{
  if(slug==='hours'){const mins=shifts.map(shiftMinutes);if(mins.some(x=>!Number.isFinite(x)||x<0))return {error:'Check shift times and make sure breaks do not exceed shift length.'};const total=mins.reduce((a,b)=>a+b,0),h=total/60,r=Number(rate);return {primary:`${Math.floor(total/60)} hr ${total%60} min`,details:[['Decimal hours',h.toFixed(2)],['Total break time',`${shifts.reduce((a,s)=>a+Number(s.breakMinutes||0),0)} min`],...(advanced&&Number.isFinite(r)&&r>=0?[['Estimated gross pay',formatCurrency(h*r,currency)]]:[])]};}
  if(slug==='time-duration'){const a=new Date(startDT),b=new Date(endDT),br=advanced?Number(durationBreak):0,mins=(b.getTime()-a.getTime())/60000-br;if(!Number.isFinite(mins)||mins<0||!Number.isFinite(br)||br<0)return {error:'End must be after start and the break cannot exceed the elapsed time.'};return {primary:`${Math.floor(mins/1440)} d ${Math.floor((mins%1440)/60)} hr ${Math.round(mins%60)} min`,details:[['Total hours',(mins/60).toFixed(2)],['Total minutes',Math.round(mins).toLocaleString()],...(advanced?[['Break deducted',`${br} min`]]:[])]};}
  if(slug==='age'){const a=dateUTC(birth),b=dateUTC(asOf);if(!a||!b||a>b)return {error:'Enter valid dates with the birth date on or before the as-of date.'};let y=b.getUTCFullYear()-a.getUTCFullYear(),m=b.getUTCMonth()-a.getUTCMonth(),d=b.getUTCDate()-a.getUTCDate();if(d<0){m--;d+=new Date(Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),0)).getUTCDate()}if(m<0){y--;m+=12}const days=Math.floor((b.getTime()-a.getTime())/MS_DAY);let next=birthdayInYear(a,b.getUTCFullYear());if(next<=b)next=birthdayInYear(a,b.getUTCFullYear()+1);return {primary:`${y} years, ${m} months, ${d} days`,details:advanced?[['Total completed months',String(y*12+m)],['Total weeks',Math.floor(days/7).toLocaleString()],['Total days',days.toLocaleString()],['Days until next birthday',Math.ceil((next.getTime()-b.getTime())/MS_DAY).toLocaleString()]]:[]};}
  const a=dateUTC(workStart),b=dateUTC(workEnd);if(!a||!b||a>b)return {error:'Enter valid dates with the end date on or after the start date.'};const excludedSet=new Set(advanced?holidays.split(',').map(x=>x.trim()).filter(Boolean):[]),weekendDays=advanced?(weekend==='fri-sat'?[5,6]:weekend==='sun'?[0]:weekend==='none'?[]:[0,6]):[0,6];let work=0,weekends=0,excludedCount=0,total=0;const last=includeEnd||!advanced?b:new Date(b.getTime()-MS_DAY);for(let x=new Date(a);x<=last;x=new Date(x.getTime()+MS_DAY)){total++;const iso=`${x.getUTCFullYear()}-${pad(x.getUTCMonth()+1)}-${pad(x.getUTCDate())}`;if(weekendDays.includes(x.getUTCDay()))weekends++;else if(excludedSet.has(iso))excludedCount++;else work++}return {primary:`${work.toLocaleString()} working days`,details:advanced?[['Calendar days included',total.toLocaleString()],['Non-working schedule days',weekends.toLocaleString()],['Entered dates excluded',excludedCount.toLocaleString()]]:[]};
 },[slug,advanced,shifts,rate,currency,startDT,endDT,durationBreak,birth,asOf,workStart,workEnd,weekend,holidays,includeEnd]);
 const field=(label:string,node:ReactNode)=><label className="advanced-field"><span>{label}</span><div>{node}</div></label>;
 return <Shell><Seo path={`/calculators/date-time/${slug}`} /><div className="advanced-calc-page"><nav aria-label="Breadcrumb" className="mono"><Link href="/">Home</Link> / <Link href="/category/date-time">Date &amp; Time</Link> / {c.title}</nav><div className="advanced-calc-layout"><header className="advanced-calc-copy"><div className="eyebrow"><span className="eyebrow-dot"/> FIGURENEST DATE &amp; TIME</div><h1>{c.title}<span>.</span></h1><p>{c.description}</p></header><section className="advanced-calculator-card"><div className="advanced-calc-head"><span className="mono">{c.title.toUpperCase()} — CALCULATE</span><div className="live-dot"><i/> LIVE RESULT</div></div><CalculatorModeSwitch advanced={advanced} onChange={setAdvanced}/><div className="advanced-fields">
 {slug==='hours'&&<>{shifts.map((s,i)=><div key={i} style={{display:'contents'}}>{field(`Shift ${i+1} clock in`,<input type="time" value={s.start} onChange={e=>setShifts(x=>x.map((v,j)=>j===i?{...v,start:e.target.value}:v))}/>)}{field(`Shift ${i+1} clock out`,<input type="time" value={s.end} onChange={e=>setShifts(x=>x.map((v,j)=>j===i?{...v,end:e.target.value}:v))}/>)}{field('Unpaid break (minutes)',<input type="number" min="0" value={s.breakMinutes} onChange={e=>setShifts(x=>x.map((v,j)=>j===i?{...v,breakMinutes:e.target.value}:v))}/>)}</div>)}{advanced&&<><button type="button" className="reset-button" onClick={()=>setShifts(x=>[...x,{start:'09:00',end:'17:00',breakMinutes:'0'}])}>Add another shift</button>{field('Hourly rate',<input type="number" min="0" step="any" value={rate} onChange={e=>setRate(e.target.value)}/>)}<CurrencySelector value={currency} onChange={n=>{prefs.setCurrency(n);prefs.setCalculatorOverride(slug,{...prefs.forCalculator(slug).calculatorOverrides[slug],currency:n})}}/></> }</>}
 {slug==='time-duration'&&<>{field('Start date and time',<input type="datetime-local" value={startDT} onChange={e=>setStartDT(e.target.value)}/>)}{field('End date and time',<input type="datetime-local" value={endDT} onChange={e=>setEndDT(e.target.value)}/>)}{advanced&&field('Unpaid break (minutes)',<input type="number" min="0" value={durationBreak} onChange={e=>setDurationBreak(e.target.value)}/>)}</>}
 {slug==='age'&&<>{field('Date of birth',<input type="date" value={birth} onChange={e=>setBirth(e.target.value)}/>)}{field('Age as of',<input type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/>)}</>}
 {slug==='working-days'&&<>{field('Start date',<input type="date" value={workStart} onChange={e=>setWorkStart(e.target.value)}/>)}{field('End date',<input type="date" value={workEnd} onChange={e=>setWorkEnd(e.target.value)}/>)}{advanced&&<>{field('Non-working weekday preset',<select value={weekend} onChange={e=>setWeekend(e.target.value)}><option value="sat-sun">Saturday + Sunday</option><option value="fri-sat">Friday + Saturday</option><option value="sun">Sunday only</option><option value="none">Every day is a working day</option></select>)}{field('Excluded dates (YYYY-MM-DD, comma separated)',<input type="text" value={holidays} placeholder="2026-09-21, 2026-09-27" onChange={e=>setHolidays(e.target.value)}/>)}<label><input type="checkbox" checked={includeEnd} onChange={e=>setIncludeEnd(e.target.checked)}/> Include end date</label></>}</>}
 </div><div className={`advanced-result ${result.error?'has-error':''}`} role="status" aria-live="polite" aria-atomic="true"><span className="mono">{result.error?'CHECK THE VALUES':'YOUR RESULT'}</span><strong>{result.error??result.primary}</strong><p>{result.error??'Calculated from the values above.'}</p></div>{!result.error&&result.details&&result.details.length>0&&<div className="advanced-breakdown">{result.details.map(([l,v])=><div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>}</section></div><div className="advanced-content-grid"><article className="advanced-content"><section><div className="eyebrow">METHOD</div><h2>How the calculation works.</h2><div className="advanced-formula-list"><div><strong>Formula</strong><code>{c.formula}</code></div></div><p>The calculator keeps the input assumptions visible so you can verify the result. Advanced mode adds planning details without changing the meaning of the basic calculation.</p></section><section><div className="eyebrow">PRACTICAL USE</div><h2>Use the result in context.</h2><p>Check that dates, clock times, breaks, non-working weekday rules and any pay assumptions match the situation you are measuring. Results are arithmetic estimates and do not determine employment rights, payroll policy, holiday entitlement or legal overtime eligibility.</p></section><section><div className="eyebrow">COMMON MISTAKES</div><h2>Checks before relying on the answer.</h2><p>Avoid mixing decimal hours with hours-and-minutes notation, forgetting unpaid breaks, using the wrong end date for an overnight period, or assuming a standard weekend or automatic holiday calendar applies everywhere. Keep the same convention throughout the calculation.</p></section><section className="advanced-faq"><div className="eyebrow">FAQ</div><h2>Common questions.</h2>{c.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></article><aside><div className="related-tools"><div className="eyebrow">RELATED TOOLS</div><Link className="advanced-aside-link" href="/calculators/date-time/time-card">Time Card Calculator</Link><Link className="advanced-aside-link" href="/calculators/salary-work/overtime">Overtime Calculator</Link><Link className="advanced-aside-link" href="/calculators/date-time/date-difference">Date Difference Calculator</Link></div></aside></div></div></Shell>;
}
