export type ExpandedCalculatorContent = {
  title: string;
  introduction: string[];
  formula: { equation: string; variables: string[] };
  examples: { heading: string; body: string }[];
  usage: string[];
  unitGuidance: string[];
  assumptions: string[];
  limitations: string[];
  mistakes: string[];
  edgeCases: string[];
  interpretation: string[];
  faqs: { question: string; answer: string }[];
  relatedLinks: { href: string; label: string; description: string }[];
};

type Page = Omit<ExpandedCalculatorContent, 'introduction' | 'usage' | 'unitGuidance' | 'assumptions' | 'limitations' | 'mistakes' | 'edgeCases' | 'interpretation'> & {
  subject: string;
  inputs: string;
  practical: string;
  units: string;
  caution: string;
};

const correctedRelatedRoutes: Record<string, string> = {
  '/converters/area': '/converters/unit',
  '/converters/volume': '/converters/unit',
  '/converters/energy': '/articles/ev-charging-and-fuel-costs',
};
const link = (href: string, label: string, description: string) => ({
  href: correctedRelatedRoutes[href] ?? href,
  label,
  description,
});

/*
 * These paragraphs deliberately live in the registry rather than the page component:
 * the calculator UI can render them as ordinary, accessible copy in any layout.
 */
const expand = (page: Page): ExpandedCalculatorContent => ({
  title: page.title,
  introduction: [page.practical],
  formula: page.formula,
  examples: page.examples,
  usage: [],
  unitGuidance: [page.units],
  assumptions: [],
  limitations: [page.caution],
  mistakes: [],
  edgeCases: [],
  interpretation: [],
  faqs: page.faqs,
  relatedLinks: page.relatedLinks,
});

const commonConstructionLinks = [
  link('/calculators/construction/square-footage', 'Square footage calculator', 'Measure rectangular surface area with an optional allowance.'),
  link('/calculators/construction/cubic-yard', 'Cubic yard calculator', 'Convert rectangular dimensions into a bulk volume.'),
  link('/articles/construction-materials-estimating', 'Construction materials estimating', 'Read practical guidance on measuring and ordering materials.'),
];

export const expandedCalculatorContent: Record<
  'percentage' | 'savings' | 'vat' | 'area' | 'volume' | 'pixels-to-cm' | 'dpi-ppi' | 'image-scaling' | 'power' | 'tile' | 'cubic-yard' | 'square-footage' | 'paint' | 'flooring' | 'mulch' | 'stair' | 'roof-pitch' | 'roofing-material' | 'board-foot',
  ExpandedCalculatorContent
> = {
  percentage: expand({ title: 'Percentage Calculator guide', subject: 'a percentage of a base value', inputs: 'a percentage and the value it applies to', practical: 'The result answers “what is this percent of that value?”; it does not calculate percentage increase or decrease.', units: 'Percent is dimensionless: 18% means 18 parts in every 100. The base can be money, people, length, or another compatible quantity, and the answer has the base’s unit.', caution: 'It does not compare an old and new value or reverse a change.', formula: { equation: 'Result = percentage × base ÷ 100', variables: ['percentage = entered percent', 'base = value after “of”', 'result = that portion of the base'] }, examples: [{ heading: 'Finding 18% of 240', body: 'Multiply 18 by 240 and divide by 100. The result is 43.2. If the base is $240, the portion is $43.20; if the base is 240 items, it is 43.2 items before any whole-item rounding.' }], faqs: [{ question: 'Is 18% the same as 0.18?', answer: 'Yes. A percent is divided by 100 before multiplying the base.' }, { question: 'Can the base be money?', answer: 'Yes; the result is in the same currency denomination.' }, { question: 'Does this find percent change?', answer: 'No. Percent change needs old and new values.' }, { question: 'Why is my answer a decimal item?', answer: 'The formula permits fractions; decide separately how whole items should be handled.' }, { question: 'Can I enter more than 100%?', answer: 'Yes. It represents more than the full base.' }], relatedLinks: [link('/calculators/finance/vat', 'VAT calculator', 'Add or remove a stated VAT rate.'), link('/calculators/finance/savings', 'Savings calculator', 'Project monthly contributions and interest.'), link('/articles/business-pricing-profit-basics', 'Business pricing basics', 'Learn how percentages appear in pricing.') ] }),
  savings: expand({ title: 'Savings Calculator guide', subject: 'a monthly savings projection', inputs: 'a starting balance, monthly contribution, annual interest rate, and saving period in years', practical: 'The model compounds monthly and treats each regular contribution as arriving at the end of the month.', units: 'Money inputs use the selected currency display. Changing currency changes denomination and formatting only; it is not foreign-exchange conversion. Rate is an annual percent and time is in years.', caution: 'Taxes, fees, withdrawal restrictions, inflation, rate changes, and investment losses are not modeled.', formula: { equation: 'Balance = start × (1 + r/12)^(12y) + contribution × [((1 + r/12)^(12y) − 1) ÷ (r/12)]', variables: ['r = annual rate as a decimal', 'y = years', 'contribution = end-of-month deposit'] }, examples: [{ heading: 'A three-year monthly plan', body: 'With a $1,200 start, $300 at each month end, and a 4.5% annual rate, the projection separates deposited principal from modeled interest. Change the rate to zero to see the no-interest deposit total.' }], faqs: [{ question: 'When are contributions added?', answer: 'The calculation assumes the end of each month.' }, { question: 'What if the rate is zero?', answer: 'The result is the starting balance plus every monthly deposit.' }, { question: 'Is this a guaranteed balance?', answer: 'No; actual rates, fees, and account terms can differ.' }, { question: 'Does currency selection convert money?', answer: 'No. It changes denomination and formatting only, not FX conversion.' }, { question: 'Does it include taxes?', answer: 'No. Consider taxes separately where applicable.' }], relatedLinks: [link('/calculators/finance/percentage', 'Percentage calculator', 'Find a portion of a value.'), link('/articles/compound-interest-guide', 'Compound interest guide', 'Understand projection assumptions.'), link('/calculators/finance/vat', 'VAT calculator', 'Work with stated tax rates.') ] }),
  vat: expand({ title: 'VAT Calculator guide', subject: 'adding or removing value-added tax', inputs: 'a price and the applicable VAT rate', practical: 'In add mode the entered price is treated as net; in remove mode it is treated as gross and divided by one plus the rate.', units: 'The rate is a percent. Money is displayed in the selected currency. Changing that selection changes denomination and formatting only; it is not foreign-exchange conversion.', caution: 'Taxability, rates, invoice rounding, registration, exemptions, and jurisdictional rules are not determined here.', formula: { equation: 'Gross = net × (1 + VAT rate ÷ 100); net = gross ÷ (1 + VAT rate ÷ 100)', variables: ['net = price before VAT', 'gross = price including VAT', 'VAT amount = gross − net'] }, examples: [{ heading: 'Adding 20% VAT', body: 'A net price of 100 at 20% becomes 120 gross. The VAT amount is 20. Removing 20% from a gross 120 returns 100, not 96, because removal uses division rather than subtraction.' }], faqs: [{ question: 'Why can’t I subtract 20% from a gross total?', answer: 'Gross includes tax on net, so remove VAT by dividing by 1.20.' }, { question: 'Which price do I enter in add mode?', answer: 'Enter the net, before-VAT price.' }, { question: 'Which price do I enter in remove mode?', answer: 'Enter the gross, VAT-inclusive price.' }, { question: 'Does currency selection perform FX conversion?', answer: 'No. It affects denomination and formatting only.' }, { question: 'Does this determine the correct VAT rate?', answer: 'No. Confirm the applicable rate and rules independently.' }], relatedLinks: [link('/calculators/finance/percentage', 'Percentage calculator', 'Calculate a percentage of a price.'), link('/articles/business-pricing-profit-basics', 'Business pricing basics', 'Consider price, cost, and tax scope.'), link('/calculators/finance/savings', 'Savings calculator', 'Plan a separate savings goal.') ] }),
  area: expand({ title: 'Area Calculator guide', subject: 'rectangular area', inputs: 'length and width in metres', practical: 'It multiplies the two entered dimensions and displays square metres.', units: 'This core calculator takes metres and returns m². For feet, inches, or other metric and imperial conversion, use the length and area converters before or after the calculation.', caution: 'It is for rectangles only; triangles, circles, and irregular outlines require appropriate geometry.', formula: { equation: 'Area = length × width', variables: ['length = one rectangular side', 'width = perpendicular rectangular side', 'area = square metres'] }, examples: [{ heading: 'A 12 m by 8 m rectangle', body: 'Multiply 12 m by 8 m to obtain 96 m². This is surface area, not perimeter: adding all four sides would answer a different question.' }], faqs: [{ question: 'What does m² mean?', answer: 'Square metres, a unit of surface area.' }, { question: 'Can I use feet?', answer: 'Convert the dimensions first or use a tool with selectable units.' }, { question: 'Does it calculate perimeter?', answer: 'No. Perimeter is 2 × length plus 2 × width.' }, { question: 'How do I handle an L shape?', answer: 'Split it into rectangles and add their areas.' }, { question: 'Why is area squared?', answer: 'It measures two dimensions multiplied together.' }], relatedLinks: [link('/converters/area', 'Area converter', 'Convert square units.'), ...commonConstructionLinks] }),
  volume: expand({ title: 'Volume Calculator guide', subject: 'rectangular volume', inputs: 'length, width, and height in metres', practical: 'It multiplies all three dimensions and displays cubic metres.', units: 'This core calculator uses metres and gives m³. Cubic units should not be confused with litres or square metres; one describes three-dimensional space, the other liquid capacity or surface.', caution: 'Cylinders, cones, irregular piles, and tapered excavations are not represented by a rectangular formula.', formula: { equation: 'Volume = length × width × height', variables: ['length, width, height = perpendicular dimensions in metres', 'volume = cubic metres'] }, examples: [{ heading: 'A 4 m by 3 m by 2.5 m space', body: 'Multiplying 4 × 3 × 2.5 gives 30 m³. If the space is not full or has sloped sides, calculate the relevant shape or use a documented average depth.' }], faqs: [{ question: 'What does m³ mean?', answer: 'Cubic metres, a measure of three-dimensional space.' }, { question: 'Is volume the same as area?', answer: 'No. Volume includes height or depth.' }, { question: 'Can I use centimetres?', answer: 'Convert all dimensions to metres first.' }, { question: 'How do I calculate a cylinder?', answer: 'Use π × radius² × height.' }, { question: 'Should I round before multiplying?', answer: 'Keep precision until the final result.' }], relatedLinks: [link('/converters/volume', 'Volume converter', 'Convert cubic units.'), ...commonConstructionLinks] }),
  'pixels-to-cm': expand({ title: 'Pixels to cm / inches guide', subject: 'pixel dimensions at a stated print resolution', inputs: 'pixels and resolution in PPI', practical: 'It divides pixels by PPI for inches, then multiplies inches by 2.54 for centimetres.', units: 'Pixels are samples, not a physical length. PPI means pixels per inch; centimetres are physical length. DPI is often used casually, but printer dots and image pixels are not always the same thing.', caution: 'It cannot assess sharpness, viewing distance, printer screening, cropping, or the image’s intended output.', formula: { equation: 'Inches = pixels ÷ PPI; centimetres = inches × 2.54', variables: ['pixels = image dimension', 'PPI = intended pixels per inch', '2.54 = centimetres per inch'] }, examples: [{ heading: '1200 pixels at 300 PPI', body: '1200 ÷ 300 is 4 inches. Multiplying by 2.54 gives 10.16 cm. A lower chosen PPI prints larger but does not create new image detail.' }], faqs: [{ question: 'Do pixels have a fixed size?', answer: 'No; physical size depends on the chosen PPI.' }, { question: 'What is 300 PPI used for?', answer: 'It is a common print-workflow target, not a universal requirement.' }, { question: 'Does resizing add detail?', answer: 'No. It can change pixel count but not recover original detail.' }, { question: 'Why show inches too?', answer: 'PPI is defined per inch, so inches are the direct intermediate result.' }, { question: 'Is PPI always the same as DPI?', answer: 'Not necessarily; they describe different parts of an output workflow.' }], relatedLinks: [link('/calculators/printing-design/dpi-ppi', 'DPI / PPI calculator', 'Calculate resolution from pixels and print width.'), link('/calculators/printing-design/image-scaling', 'Image scaling calculator', 'Resize while retaining aspect ratio.'), link('/articles/unit-conversion-basics', 'Unit conversion basics', 'Review conversion practice.') ] }),
  'dpi-ppi': expand({ title: 'DPI / PPI Calculator guide', subject: 'print resolution from a pixel width and printed width', inputs: 'pixel width and physical print width in inches', practical: 'It divides pixel width by print width to return PPI.', units: 'The input width is inches and the output is PPI, pixels per inch. PPI describes image sampling; a printer’s DPI specification can refer to deposited dots and should not automatically be substituted.', caution: 'One dimension alone does not validate the image height, crop, printer, paper, or viewing-distance requirements.', formula: { equation: 'PPI = pixel width ÷ print width in inches', variables: ['pixel width = image samples across', 'print width = intended physical width', 'PPI = pixels per inch'] }, examples: [{ heading: '2400 pixels across 8 inches', body: 'Dividing 2400 by 8 gives 300 PPI. Printing the same file at 12 inches instead gives 200 PPI because the available pixels are spread across a wider surface.' }], faqs: [{ question: 'What happens if print width is zero?', answer: 'Resolution is undefined because division by zero is not valid.' }, { question: 'Can I enter centimetres?', answer: 'Convert the print width to inches before using this calculator.' }, { question: 'Does 300 PPI guarantee quality?', answer: 'No. Subject detail, processing, printer, and viewing conditions matter.' }, { question: 'Why does a larger print lower PPI?', answer: 'The same pixel count is distributed over more inches.' }, { question: 'Is DPI identical to PPI?', answer: 'They are often used informally, but image pixels and printer dots differ.' }], relatedLinks: [link('/calculators/printing-design/pixels-to-cm', 'Pixels to cm / inches', 'Find physical size at a chosen PPI.'), link('/calculators/printing-design/image-scaling', 'Image scaling calculator', 'Calculate proportional dimensions.'), link('/articles/unit-conversion-basics', 'Unit conversion basics', 'Review inches and centimetres.') ] }),
  'image-scaling': expand({ title: 'Image Scaling Calculator guide', subject: 'proportional image resizing', inputs: 'original width, original height, and new width in pixels', practical: 'It applies the width scale factor to the original height, preserving the original aspect ratio.', units: 'All fields are pixels. Pixel dimensions control the file raster size; they are not a print size unless a PPI and physical output size are also chosen.', caution: 'It does not crop, choose a resampling method, alter file size, or judge visual quality after enlargement.', formula: { equation: 'New height = original height ÷ original width × new width', variables: ['original width and height = source pixel dimensions', 'new width = requested pixel width', 'new height = proportional result'] }, examples: [{ heading: '2400 × 1600 resized to 1200 wide', body: 'The width is halved, so the height is also halved: 1600 ÷ 2400 × 1200 = 800 pixels. The output is 1200 × 800 and has the same 3:2 aspect ratio.' }], faqs: [{ question: 'Why must original width be greater than zero?', answer: 'It is the divisor in the scale factor.' }, { question: 'Will this crop my image?', answer: 'No. It preserves the whole original proportion.' }, { question: 'Can I scale by height?', answer: 'Calculate the reciprocal relationship or use height as the target in equivalent math.' }, { question: 'Does enlarging improve detail?', answer: 'No. Interpolation may add pixels but cannot restore source detail.' }, { question: 'Why can height be fractional?', answer: 'The exact proportional value may not be a whole pixel; choose a practical rounded dimension.' }], relatedLinks: [link('/calculators/printing-design/pixels-to-cm', 'Pixels to cm / inches', 'Connect pixels with a print resolution.'), link('/calculators/printing-design/dpi-ppi', 'DPI / PPI calculator', 'Find pixels per inch.'), link('/articles/unit-conversion-basics', 'Unit conversion basics', 'Review measurement conversions.') ] }),
  power: expand({ title: 'Power HP / kW Converter guide', subject: 'engine power conversion', inputs: 'a power value and source and destination units', practical: 'The converter uses a common power basis to translate watts, kilowatts, megawatts, and horsepower.', units: 'One mechanical horsepower is approximately 0.745699872 kW in this converter. Use the unit specified by the engine, motor, test standard, or supplier; power is not energy, which is measured in kWh or joules.', caution: 'It does not compare torque curves, efficiency, drivetrain losses, battery capacity, legal ratings, or real vehicle performance.', formula: { equation: 'kW = horsepower × 0.745699872', variables: ['horsepower = entered mechanical horsepower', 'kW = kilowatts', 'power = rate of energy transfer'] }, examples: [{ heading: '100 horsepower', body: 'Multiplying 100 by 0.745699872 gives about 74.57 kW. A rounded label may show 75 kW, but retain the stated source rating when a specification requires it.' }], faqs: [{ question: 'Is power the same as energy?', answer: 'No. Power is a rate; energy accumulates over time.' }, { question: 'How many kW is 100 hp?', answer: 'About 74.57 kW using mechanical horsepower.' }, { question: 'Why do ratings differ?', answer: 'Measurement standard, conditions, and whether output is engine or wheel power can differ.' }, { question: 'Can I use this for electrical equipment?', answer: 'It converts units, but equipment requirements need voltage, current, and efficiency context.' }, { question: 'Does it predict acceleration?', answer: 'No. Vehicle mass, gearing, traction, and many other factors matter.' }], relatedLinks: [link('/calculators/automotive/ev-charging-time', 'EV charging time calculator', 'Estimate time from kWh and kW.'), link('/converters/energy', 'Energy converter', 'Convert energy units.'), link('/articles/ev-charging-and-fuel-costs', 'EV charging and fuel costs', 'Explore vehicle energy assumptions.') ] }),
  tile: expand({ title: 'Tile Calculator guide', subject: 'tile quantity for a rectangular surface', inputs: 'surface length and width, tile length and width, and cutting waste percentage', practical: 'It divides adjusted surface area by one tile’s face area and rounds the tile count upward.', units: 'The construction tool supports matching metric and imperial dimensions, including feet/metres for the surface and inches/centimetres for tile. Keep tile and surface measurements within the selected system.', caution: 'Grout joints, box coverage, pattern direction, trim pieces, substrate preparation, and layout-specific cuts require separate review.', formula: { equation: 'Tiles = ceiling(surface area × (1 + waste/100) ÷ tile area)', variables: ['surface area = length × width', 'tile area = tile length × tile width', 'waste = cutting allowance'] }, examples: [{ heading: 'A 120 ft² floor with 12 in tiles', body: 'A 12 in × 12 in tile covers one square foot by face size. At 10% waste, 120 × 1.10 gives 132 tiles before converting to full boxes.' }], faqs: [{ question: 'Why is the tile count rounded up?', answer: 'Tiles are purchased as whole pieces or boxes.' }, { question: 'What waste is appropriate?', answer: 'Straight layouts often use about 10%; complex layouts can need more.' }, { question: 'Does this include grout?', answer: 'No. Estimate grout separately using the product guidance.' }, { question: 'Should I subtract cabinets?', answer: 'Exclude permanent areas that will not receive tile.' }, { question: 'Why buy full boxes?', answer: 'Retail packaging and dye-lot consistency make box coverage relevant.' }], relatedLinks: [link('/calculators/construction/flooring', 'Flooring calculator', 'Estimate floor coverage area.'), ...commonConstructionLinks] }),
  'cubic-yard': expand({ title: 'Cubic Yard Calculator guide', subject: 'rectangular bulk-material volume', inputs: 'length, width, and depth', practical: 'It converts the dimensions to a shared basis and reports cubic yards and cubic metres.', units: 'Imperial dimensions use feet with depth commonly entered in inches; metric dimensions use metres and centimetres. One cubic yard is 27 cubic feet. Volume is not weight: soil, gravel, mulch, and concrete have different densities.', caution: 'Compaction, moisture, settling, product density, supplier load increments, and non-rectangular shapes are excluded.', formula: { equation: 'Cubic yards = length(ft) × width(ft) × depth(ft) ÷ 27', variables: ['length and width = plan dimensions', 'depth = finished material depth', '27 = cubic feet per cubic yard'] }, examples: [{ heading: 'A 15 ft × 8 ft bed, 3 in deep', body: 'Convert 3 in to 0.25 ft. Then 15 × 8 × 0.25 ÷ 27 is about 1.11 yd³ before an allowance for settling or waste.' }], faqs: [{ question: 'How many cubic feet are in a yard?', answer: 'There are 27 cubic feet in one cubic yard.' }, { question: 'Does a cubic yard have a fixed weight?', answer: 'No. Weight depends on material density and moisture.' }, { question: 'Should depth be compacted?', answer: 'Use the finished depth required by the project.' }, { question: 'Can I use this for a circular bed?', answer: 'Use a circle-area formula before applying depth.' }, { question: 'Why add extra material?', answer: 'Settling, spillage, and supplier increments can affect an order.' }], relatedLinks: commonConstructionLinks }),
  'square-footage': expand({ title: 'Square Footage Calculator guide', subject: 'surface area for equal rectangular spaces', inputs: 'length, width, number of equal areas, and waste allowance', practical: 'It multiplies one rectangle by the count, then applies the selected allowance for a purchase-area estimate.', units: 'The construction calculator displays both ft² and m² and can use imperial feet or metric metres. Area conversion is squared: 1 m² is about 10.764 ft², not 3.281 ft².', caution: 'Unequal rooms, curved spaces, openings, product box coverage, and installation conditions must be measured or handled separately.', formula: { equation: 'Purchase area = length × width × count × (1 + waste/100)', variables: ['count = identical areas', 'waste = material allowance', 'area = finished surface'] }, examples: [{ heading: 'Two 16 ft × 12 ft rooms', body: 'One room is 192 ft². Two equal rooms are 384 ft²; applying 10% gives 422.4 ft² of purchase area before converting that figure to packages.' }], faqs: [{ question: 'How do I measure an L-shaped room?', answer: 'Split it into rectangles and add the sections.' }, { question: 'Does count mean rooms?', answer: 'It duplicates the entered rectangle, so use it only for equal areas.' }, { question: 'What is waste for?', answer: 'It allows for cutting and installation loss, not a measurement guess.' }, { question: 'Can I calculate wall area?', answer: 'Use appropriate wall dimensions and subtract openings separately.' }, { question: 'Why see metric and imperial?', answer: 'Products and plans commonly use either system.' }], relatedLinks: [link('/calculators/construction/tile', 'Tile calculator', 'Turn surface area into tile count.'), link('/calculators/construction/paint', 'Paint calculator', 'Estimate wall paint.'), ...commonConstructionLinks] }),
  paint: expand({ title: 'Paint Calculator guide', subject: 'wall-paint container quantity', inputs: 'room length, width, wall height, opening area, coats, and product coverage', practical: 'It calculates wall perimeter times height, subtracts unpainted openings, multiplies by coats, and divides by coverage.', units: 'Imperial coverage is ft² per gallon; metric coverage is m² per litre. Use the coverage printed for the actual paint, surface, application method, and coat type.', caution: 'Ceilings, trim, primer, texture, porosity, color change, repair work, and container sizes are outside the formula.', formula: { equation: 'Containers = ((2 × (length + width) × height − openings) × coats) ÷ coverage', variables: ['openings = areas not painted', 'coats = complete applications', 'coverage = area per container'] }, examples: [{ heading: 'A 16 ft × 12 ft room', body: 'With 8 ft walls, 60 ft² of openings, two coats, and 350 ft² per gallon, the modeled need is about 2.22 gallons. Purchase whole containers after checking label coverage.' }], faqs: [{ question: 'Does this include ceilings?', answer: 'No. Add the ceiling separately if it will be painted.' }, { question: 'Why does coverage vary?', answer: 'Surface texture, porosity, color, and application affect real coverage.' }, { question: 'Should primer count as a coat?', answer: 'Estimate primer separately unless its product instructions say otherwise.' }, { question: 'Do I subtract windows?', answer: 'Subtract openings that will not be painted.' }, { question: 'Why round up?', answer: 'Paint is normally sold in whole containers.' }], relatedLinks: [link('/calculators/construction/square-footage', 'Square footage calculator', 'Measure a separate surface.'), ...commonConstructionLinks] }),
  flooring: expand({ title: 'Flooring Calculator guide', subject: 'flooring purchase area', inputs: 'room length, width, number of equal rooms, and waste allowance', practical: 'It multiplies the equal room areas and increases the result by the selected cutting allowance.', units: 'Results are available in ft² and m². Match the result to the product’s stated box coverage and do not use linear feet for a floor-area purchase.', caution: 'Box counts, pattern repeats, transitions, subfloor condition, underlayment, acclimation, and installation instructions are not calculated.', formula: { equation: 'Purchase area = length × width × room count × (1 + waste/100)', variables: ['room count = equal rooms only', 'waste = cutting allowance', 'purchase area = material coverage target'] }, examples: [{ heading: 'One 16 ft × 12 ft room', body: 'The net room area is 192 ft². At 10% waste, the material target is 211.2 ft². Divide by the coverage printed on each box and round to whole boxes.' }], faqs: [{ question: 'How much flooring waste is typical?', answer: 'Simple layouts often use 5–10%; complex cuts can require more.' }, { question: 'Does this include underlayment?', answer: 'No. Order it from its own product coverage and instructions.' }, { question: 'Can I use it for unequal rooms?', answer: 'Calculate each room separately and add results.' }, { question: 'Why not round the area first?', answer: 'Keeping decimals reduces accumulated rounding error.' }, { question: 'Should closets be included?', answer: 'Include finished areas that will receive the flooring.' }], relatedLinks: [link('/calculators/construction/tile', 'Tile calculator', 'Estimate tile pieces.'), ...commonConstructionLinks] }),
  mulch: expand({ title: 'Mulch Calculator guide', subject: 'garden-bed mulch volume and bag count', inputs: 'bed length, width, depth, bag size, and allowance', practical: 'It finds bed volume, applies the allowance, and divides by the stated bag volume.', units: 'Imperial inputs use feet, inches, and cubic feet; metric inputs use metres, centimetres, and litres. Bulk mulch may be sold by cubic yard or cubic metre, while bags use their labeled volume.', caution: 'Settling, moisture, bed shape, existing mulch, delivery minimums, and horticultural suitability are not determined by the calculator.', formula: { equation: 'Bags = bed area × depth × (1 + allowance/100) ÷ bag volume', variables: ['depth = desired finished mulch depth', 'bag volume = label capacity', 'allowance = settling and handling margin'] }, examples: [{ heading: 'A 20 ft × 6 ft bed at 3 in', body: 'The base volume is about 1.11 yd³. With 10% extra and 2 ft³ bags, the estimate rounds to 17 bags. Confirm the bag volume because products vary.' }], faqs: [{ question: 'How deep should mulch be?', answer: 'Many beds use roughly 2–4 inches; follow plant and local guidance.' }, { question: 'Does mulch settle?', answer: 'Yes, and an allowance can help account for it.' }, { question: 'Can I use cubic yards for bags?', answer: 'Convert volume consistently before dividing.' }, { question: 'Should I mulch against a trunk?', answer: 'Keep mulch away from trunks and siding as appropriate.' }, { question: 'Do I measure an irregular bed differently?', answer: 'Break it into simple sections and add the volumes.' }], relatedLinks: [link('/calculators/construction/cubic-yard', 'Cubic yard calculator', 'Estimate bulk volume.'), ...commonConstructionLinks] }),
  stair: expand({ title: 'Stair Calculator guide', subject: 'a straight-stair layout starting point', inputs: 'total floor-to-floor rise, maximum riser height, and minimum tread depth', practical: 'It rounds riser count up, divides total rise by that count, sets treads to one less than risers, and multiplies treads by minimum tread depth.', units: 'Use inches in imperial mode or centimetres in metric mode. Finished-floor to finished-floor rise must use the same basis as the proposed finished treads and landings.', caution: 'It does not check local building code, headroom, width, landings, nosings, guard requirements, stringer design, or accessibility rules.', formula: { equation: 'Risers = ceiling(total rise ÷ maximum riser); run = (risers − 1) × minimum tread', variables: ['total rise = finished floor-to-floor height', 'riser = vertical step height', 'tread = horizontal walking depth'] }, examples: [{ heading: 'A 108 in rise', body: 'At a 7.5 in maximum riser, use 15 risers. Actual riser height is 108 ÷ 15 = 7.2 in. With 10 in treads, 14 treads create 140 in of run.' }], faqs: [{ question: 'Why are treads one fewer than risers?', answer: 'The upper floor generally serves as the final walking surface.' }, { question: 'Does this pass code?', answer: 'No. Verify the complete design against local requirements.' }, { question: 'What is floor-to-floor rise?', answer: 'The vertical distance between finished lower and upper floors.' }, { question: 'Can I change tread depth?', answer: 'Yes; use the applicable minimum or chosen layout depth.' }, { question: 'Are all risers equal?', answer: 'The formula makes them equal; construction must maintain consistent finished dimensions.' }], relatedLinks: [link('/calculators/construction/roof-pitch', 'Roof pitch calculator', 'Work with rise and run.'), ...commonConstructionLinks] }),
  'roof-pitch': expand({ title: 'Roof Pitch Calculator guide', subject: 'roof pitch, angle, and slope multiplier', inputs: 'rise and horizontal run', practical: 'It divides rise by run, expresses the ratio as rise per 12, calculates the arctangent angle, and calculates the sloped-area multiplier.', units: 'Rise and run may be inches or centimetres, but they must be the same unit because pitch is a ratio. A 6:12 label means six units of rise for twelve horizontal units.', caution: 'It does not assess roof structure, loads, drainage, covering suitability, access safety, local code, or a complex roof’s actual surface area.', formula: { equation: 'Pitch = rise ÷ run; angle = arctan(pitch); multiplier = √(1 + pitch²)', variables: ['rise = vertical change', 'run = horizontal distance', 'multiplier = sloped area ÷ plan area'] }, examples: [{ heading: 'A 6 in rise over 12 in run', body: 'The pitch is 6:12, the angle is about 26.6°, and the multiplier is about 1.118. Multiply plan area by this multiplier to estimate the simple sloped surface.' }], faqs: [{ question: 'What does 6:12 mean?', answer: 'Six units of rise for every twelve horizontal units of run.' }, { question: 'Is run rafter length?', answer: 'No. Run is horizontal distance.' }, { question: 'Can I use centimetres?', answer: 'Yes, if rise and run use the same unit.' }, { question: 'What is a slope multiplier?', answer: 'It converts plan-view area to sloped area for a simple plane.' }, { question: 'Is it safe to measure on a roof?', answer: 'Use appropriate safety practices; do not rely on a calculator for access decisions.' }], relatedLinks: [link('/calculators/construction/roofing-material', 'Roofing material calculator', 'Estimate sloped roof coverage.'), ...commonConstructionLinks] }),
  'roofing-material': expand({ title: 'Roofing Material Calculator guide', subject: 'simple roof surface, squares, and shingle bundles', inputs: 'plan length, plan width, roof rise, roof run, and waste allowance', practical: 'It multiplies plan area by the pitch multiplier, adds waste, converts the result to roofing squares, and uses three bundles per typical square.', units: 'Plan dimensions can be feet/metres and rise/run inches/centimetres in the selected construction system. A roofing square is 100 ft² of roof surface, not 100 ft² of plan area.', caution: 'Dormers, valleys, hips, ridges, eaves, starter, caps, flashing, underlayment, bundle coverage, wind requirements, and local rules need separate takeoffs.', formula: { equation: 'Adjusted area = plan area × √(1 + (rise/run)²) × (1 + waste/100)', variables: ['plan area = length × width', 'rise/run = roof slope', 'one square = 100 ft² of roof surface'] }, examples: [{ heading: 'A 40 ft × 28 ft roof at 6:12', body: 'The simple sloped area is about 1,252 ft². Adding 10% produces about 13.77 squares, or 42 bundles at three bundles per square; verify the manufacturer’s actual bundle coverage.' }], faqs: [{ question: 'What is a roofing square?', answer: 'It is 100 square feet of roof surface.' }, { question: 'Why use pitch?', answer: 'Sloped surface is larger than its horizontal footprint.' }, { question: 'Are three bundles always a square?', answer: 'No. Confirm coverage for the specific shingle product.' }, { question: 'Does it include ridge caps?', answer: 'No. Take off caps, starter, and flashing separately.' }, { question: 'Can I combine roof sections?', answer: 'Calculate distinct planes separately for a clearer estimate.' }], relatedLinks: [link('/calculators/construction/roof-pitch', 'Roof pitch calculator', 'Find slope multiplier.'), ...commonConstructionLinks] }),
  'board-foot': expand({ title: 'Board Foot Calculator guide', subject: 'lumber volume in board feet', inputs: 'board thickness, width, length, and quantity', practical: 'It multiplies thickness in inches, width in inches, length in feet, and board count, then divides by 12.', units: 'Imperial board feet use inches for thickness and width and feet for length. Metric entries are converted to the same volume basis. A board foot is 144 cubic inches, not a linear foot.', caution: 'Nominal versus actual dimensions, grading, defects, kerf, trim, moisture movement, pricing, structural capacity, and stock availability are not calculated.', formula: { equation: 'Board feet = thickness(in) × width(in) × length(ft) × quantity ÷ 12', variables: ['thickness and width = board dimensions', 'length = board length', 'quantity = number of identical boards'] }, examples: [{ heading: 'Twelve 2 in × 8 in × 8 ft boards', body: '2 × 8 × 8 × 12 ÷ 12 equals 128 board feet. For a purchasing estimate, use actual surfaced dimensions where the seller prices or specifies them that way.' }], faqs: [{ question: 'What is a board foot?', answer: 'A volume equal to 144 cubic inches.' }, { question: 'Is it a linear foot?', answer: 'No. It includes thickness, width, and length.' }, { question: 'Should I use nominal size?', answer: 'Use the dimensions relevant to the supplier’s pricing and specification.' }, { question: 'Can I enter metric lumber?', answer: 'Yes; the construction tool converts metric dimensions.' }, { question: 'Does this include waste?', answer: 'No. Add a separate allowance for cuts and defects.' }], relatedLinks: [link('/calculators/construction/flooring', 'Flooring calculator', 'Estimate surface coverage.'), ...commonConstructionLinks] }),
};