import type { ExpandedCalculatorContent } from './expanded-calculator-content';

type FocusedSlug = 'deck-material' | 'fence-material' | 'drywall' | 'brick' | 'gravel';

const related = (href: string, label: string, description: string) => ({ href, label, description });

export const focusedConstructionContent: Record<FocusedSlug, ExpandedCalculatorContent> = {
  'deck-material': {
    title: 'Deck Material Calculator guide',
    introduction: [
      'A deck-board order starts with the finished walking surface, not with the framing plan or the nominal label on a board. This calculator estimates the field boards needed when parallel boards cross a rectangular deck. It accounts for the face width actually covered by each board, the deliberate gap between boards, the stock length that creates butt joints, and a cutting allowance. That makes it useful for an early quantity check before comparing suppliers or layouts.',
      'Measure the exposed deck length in the direction a board runs and the deck width across the rows. Exclude stairs, picture-frame borders, fascia, and separate landings because their board direction and cuts differ. Enter the manufacturer’s actual face width; a nominal 6-inch wood board is commonly narrower after surfacing, and composite products have their own published dimensions. The result is a stock-board count, not a structural design or a complete deck package.'
    ],
    formula: {
      equation: 'Boards across = ceiling(deck width ÷ (board width + gap)). Boards per row = ceiling(deck length ÷ stock board length). Total boards = product × (1 + waste).',
      variables: ['deck width = dimension perpendicular to the boards', 'board width + gap = coverage consumed by one installed row', 'stock board length = purchasable board length', 'waste = cutting waste percentage']
    },
    examples: [
      { heading: '20 ft by 12 ft deck with 16 ft boards', body: 'Convert the 5.5-inch board face and 1/8-inch gap into a 5.625-inch row module. A 12-foot width needs ceiling(144 ÷ 5.625), or 26 rows. Each 20-foot row needs ceiling(20 ÷ 16), or two boards. The base count is 52; multiplying by 1.10 produces 57.2, so a whole-board purchase rounds to 58 boards.' },
      { heading: 'Metric composite layout', body: 'For a 6.0 m by 3.6 m deck, 140 mm boards, 3 mm gaps, and 4.8 m stock, the row module is 143 mm. The width needs ceiling(3,600 ÷ 143), or 26 rows, and each row needs two boards. With 8% cutting waste, 52 × 1.08 is 56.16, so plan for 57 whole stock boards before any border treatment.' }
    ],
    usage: ['Sketch the finished rectangular field and identify the direction each deck board will run.', 'Measure length along the boards and width across them; split L-shaped decks into rectangles rather than averaging dimensions.', 'Enter actual board face width, the manufacturer-required gap, available stock length, and a defensible cutting-waste percentage.', 'Read boards across and boards per row as a layout check, then use the total as the field-board purchasing starting point.', 'Calculate borders, stair treads, fascia, blocking, clips, screws, joists, beams, posts, and footings separately.'],
    unitGuidance: ['Imperial entries use feet for deck and stock lengths and inches for board width and gap. Metric entries use metres for the deck and stock length and millimetres for the board and gap.', 'Do not add a 5.5-inch board width directly to a gap written as 3 mm. The calculator converts selected construction units, but a hand check must use one basis.', 'Area is shown for orientation, while the board result depends on linear layout and cannot be replaced simply by dividing area by board face area.'],
    assumptions: ['The deck field is rectangular and boards are laid in straight, parallel rows.', 'Every row uses the same board width, gap, and stock length.', 'The formula permits butt joints anywhere a row exceeds stock length and does not optimize cut nesting.', 'Waste is applied after the base board count exactly as entered.'],
    limitations: ['It does not size framing, verify spans, calculate loads, or establish code-compliant attachment and guard requirements.', 'Expansion gaps at end joints, concealed-fastener rules, grain direction, color matching, and product-specific maximum overhangs remain installer decisions.', 'A diagonal herringbone pattern, curved edge, or picture frame needs a separate takeoff because row lengths and offcuts change materially.'],
    mistakes: ['Using nominal instead of actual face width overstates coverage or understates rows.', 'Entering board length as the deck width reverses the layout logic.', 'Treating the gap as optional overlooks the space consumed by every row.', 'Rounding the calculated total down before checking stock availability can leave an incomplete final row.'],
    edgeCases: ['A deck exactly divisible by the row module still follows the ceiling rule; confirm whether the last edge needs a trim rip.', 'A very short deck may need only one stock board per row, but waste remains relevant for damaged or selected boards.', 'For mixed stock lengths, calculate a cut plan separately rather than assuming one length optimizes every row.', 'If a border interrupts field rows, measure the reduced field rectangle instead of the outside deck dimensions.'],
    interpretation: ['The total is an estimate of purchasable full boards for the main field. A result of 57.2 means 58 boards when only whole boards are sold.', 'Compare the board count with the displayed coverage area as a sanity check, not as a substitute for the row calculation.', 'If a modest change in stock length sharply changes boards per row, obtain prices for both lengths before ordering.', 'Keep the chosen gap and product profile with the estimate because they directly determine the count.'],
    faqs: [
      { question: 'Why is the board gap included?', answer: 'Each installed row occupies its board face plus its spacing gap, so omitting the gap can undercount rows.' },
      { question: 'Does this include picture-frame decking?', answer: 'No. Take off border boards separately because they run in another direction.' },
      { question: 'Should I add 10% waste?', answer: 'Ten percent is a planning allowance, not a universal rule; adjust it for layout complexity, board quality, and reusable offcuts.' },
      { question: 'Can I use composite boards?', answer: 'Yes, provided you enter the manufacturer’s actual face width, gap, and available stock length.' },
      { question: 'Does this calculate joists?', answer: 'No. Framing needs a span, load, fastening, and local-code review.' }
    ],
    relatedLinks: [related('/calculators/construction/board-foot', 'Board Foot Calculator', 'Estimate lumber volume.'), related('/calculators/construction/fence-material', 'Fence Material Calculator', 'Plan fence components.'), related('/articles/construction-materials-estimating', 'Construction materials estimating', 'Learn practical ordering methods.')]
  },
  'fence-material': {
    title: 'Fence Material Calculator guide',
    introduction: [
      'Fence quantities are governed by the line being fenced, the maximum distance between posts, and the repeating picket module, rather than by lot area. This calculator turns a straight measured run into a preliminary count of posts, pickets, rails, and sections. It is especially helpful when comparing a privacy-fence sketch with a supplier list, because gates receive their own pair of supporting posts and rail count follows the number of sections.',
      'Use the actual fence route, including changes in direction and offsets, instead of copying a property dimension that the fence will not follow. Enter installed face width and the intended picket gap, not a nominal product description. Gate openings are treated conservatively in the post total, while pickets use the complete entered fence length; subtract gate lengths manually for a refined picket order. Final post sizing, embedment, and permissions require site-specific judgment.'
    ],
    formula: {
      equation: 'Posts = ceiling(length ÷ spacing) + 1 + 2 × gates. Pickets = ceiling(length ÷ (picket width + gap)). Rails = sections × rails per section.',
      variables: ['length = measured fence run', 'spacing = planned maximum post spacing', 'gates = gate openings', 'sections = ceiling(length ÷ spacing)', 'picket width + gap = repeating picket module']
    },
    examples: [
      { heading: '100-foot privacy fence with one gate', body: 'At 8-foot spacing, ceiling(100 ÷ 8) is 13 sections. The base post count is 13 + 1, or 14. One gate adds two side posts for 16 posts. With 5.5-inch pickets and 1/8-inch gaps, ceiling(1,200 ÷ 5.625) gives 214 pickets before removing any gate-width pickets. Three rails per section produces 39 rail runs.' },
      { heading: 'Thirty-metre run without gates', body: 'For a 30 m fence spaced at 2.4 m, ceiling(30 ÷ 2.4) is 13 sections and 14 posts. Pickets with a 140 mm face and 3 mm gap use a 143 mm module; ceiling(30,000 ÷ 143) is 210 pickets. If the design specifies two rails per section, the rail estimate is 13 × 2, or 26 runs.' }
    ],
    usage: ['Walk and mark the intended fence alignment, corners, ends, grade changes, and every proposed gate.', 'Measure each straight segment; use separate calculations when spacing, height, or picket style changes.', 'Enter run length, finished height, post spacing, actual picket face, gap, rails per section, and gate count.', 'Use the section count implied by ceiling(length ÷ spacing) when ordering rails or panels.', 'Add corner, terminal, bracing, hardware, concrete, and gate materials from the plan and supplier instructions.'],
    unitGuidance: ['Imperial fence runs, heights, and spacing are in feet, with picket widths and gaps in inches. Metric work uses metres and millimetres respectively.', 'A picket gap must share the picket-width basis before calculating its repeating module.', 'Fence height informs the project description but does not alter the stated post, picket, or rail equations; it does affect the product and structural design selected.'],
    assumptions: ['Post spacing is uniform and no spacing exceeds the entered value.', 'A normal run has an end post at both ends, reflected by the plus one.', 'Each gate needs two additional posts.', 'Every section receives the same number of rails.'],
    limitations: ['The estimate does not deduct gate width from pickets, so it is intentionally conservative for that line item.', 'It does not determine post depth, concrete volume, slope stepping, wind resistance, or boundary legality.', 'Prefabricated panels, shared corner posts, double gates, and special braced terminals may have different component rules.'],
    mistakes: ['Counting posts as length divided by spacing without the end post misses a terminal.', 'Forgetting that gates add two sides understates support materials.', 'Using centre-to-centre panel width as picket face width creates a wrong picket count.', 'Assuming rails are total fence length divided by rail stock length ignores sections and splice planning.'],
    edgeCases: ['A run shorter than the spacing still needs two end posts, because ceiling of a positive fraction is one.', 'At a corner, one post can serve intersecting runs only when the chosen layout and hardware allow it.', 'Sloped ground may require stepped panels or racked pickets, changing cut waste.', 'For a gate at an end, confirm whether an existing terminal post replaces one of the added gate posts.'],
    interpretation: ['Treat posts as a preliminary component total, then label which are line, corner, end, and gate posts.', 'The picket answer is a full-run coverage count; refine it by subtracting openings and adding damaged-picket allowance as appropriate.', 'Rails are counted as section runs, not as purchasable stock pieces, so divide or optimize against sold lengths afterward.', 'An unexpectedly high section count usually signals that spacing or units deserve another check.'],
    faqs: [
      { question: 'Why do gates add two posts?', answer: 'A gate normally needs one support on each side, though heavy gates may need a stronger design.' },
      { question: 'Are gate pickets deducted?', answer: 'No. The calculator uses the full run for a conservative quick estimate; subtract gate widths for a detailed takeoff.' },
      { question: 'Does it calculate concrete?', answer: 'No. Hole diameter, depth, soil, frost conditions, and post design must be assessed separately.' },
      { question: 'What is a section?', answer: 'It is one span between posts, calculated here by rounding the run divided by post spacing upward.' },
      { question: 'Can I use it for a curved fence?', answer: 'Break the curve into measured short segments and review the layout and post positions on site.' }
    ],
    relatedLinks: [related('/calculators/construction/deck-material', 'Deck Material Calculator', 'Estimate field deck boards.'), related('/calculators/construction/board-foot', 'Board Foot Calculator', 'Calculate lumber volume.'), related('/articles/construction-materials-estimating', 'Construction materials estimating', 'Plan a clearer material takeoff.')]
  },
  'drywall': {
    title: 'Drywall Calculator guide',
    introduction: [
      'Drywall sheets are purchased by face area, but a room has several surfaces and openings that make a quick floor-area estimate misleading. This calculator combines the perimeter walls and ceiling of a rectangular room, removes the entered opening area, applies cutting waste, and divides by one sheet’s face area. It provides a transparent preliminary sheet count for rooms being boarded on the listed surfaces.',
      'Measure finished room length, width, and wall height. Enter doors and windows only where they will not receive board, using their actual opening area. Choose the sheet dimensions you intend to buy; longer sheets can reduce butt joints yet may change handling and delivery needs. The calculation does not decide whether a ceiling, a partition’s opposite face, soffits, returns, or specialized board should be included, so list those surfaces deliberately.'
    ],
    formula: {
      equation: 'Drywall area = wall perimeter × height + ceiling area − openings. Sheets = drywall area × (1 + waste ÷ 100) ÷ sheet area.',
      variables: ['wall perimeter = 2 × (room length + room width)', 'ceiling area = room length × room width', 'openings = unboarded door and window area', 'sheet area = sheet length × sheet width']
    },
    examples: [
      { heading: '16 ft by 12 ft room with an 8 ft ceiling', body: 'Wall perimeter is 2 × (16 + 12), or 56 ft. Walls are 56 × 8 = 448 ft² and the ceiling is 192 ft². After subtracting 60 ft² of openings, the modeled area is 580 ft². With 4 ft by 8 ft sheets and 10% waste, 580 × 1.10 ÷ 32 is 19.94, so order 20 sheets.' },
      { heading: 'Metric room using 2.4 m by 1.2 m sheets', body: 'A 4.8 m by 3.6 m room, 2.4 m high, has 40.8 m of wall perimeter times height, or 40.32 m², plus 17.28 m² ceiling area. Subtract 5.0 m² openings for 52.6 m². At 12% waste, divide 58.912 m² by 2.88 m² per sheet: the practical whole-sheet result is 21.' }
    ],
    usage: ['Decide which walls and ceilings will receive drywall; calculate separate rooms or surfaces rather than combining unlike work.', 'Measure length, width, finished wall height, and all unboarded openings.', 'Enter the exact sheet length and width available for the selected board type.', 'Add an allowance for cuts, layout, damage, and offcuts, then round the result up to whole sheets.', 'Make a sheet-layout sketch and separately count joint tape, compound, screws, trim, insulation, and specialty boards.'],
    unitGuidance: ['Imperial dimensions use feet and opening area uses square feet; metric dimensions use metres and square metres.', 'Sheet length and width create sheet area, so do not confuse a 4 by 8 foot sheet with 32 linear feet.', 'Keep metric sheet dimensions in metres rather than entering millimetres as whole metres when checking calculations manually.'],
    assumptions: ['The room is rectangular with vertical walls and one flat ceiling.', 'All modeled wall and ceiling surfaces receive the same sheet product.', 'Opening area is accurately measured and does not require separate return pieces.', 'Waste applies to the net board area after openings are subtracted.'],
    limitations: ['The formula does not select sheet orientation, seam placement, fastener schedule, board thickness, or fire and moisture ratings.', 'It does not automatically include both sides of an interior partition, closets, bulkheads, or window reveals.', 'Local requirements and manufacturer directions govern installation and should override a quantity convenience.'],
    mistakes: ['Using floor area alone omits walls and seriously understates a wall-and-ceiling job.', 'Subtracting openings twice, once from walls and again from the total, gives too few sheets.', 'Choosing a nominal sheet size different from the stocked product invalidates the divisor.', 'Rounding net sheets before waste can lose needed material.'],
    edgeCases: ['If openings exceed wall area, the calculator prevents negative cover area, but recheck the measurements because the scope may be wrong.', 'Vaulted ceilings and sloped walls need their actual surface areas, not a flat ceiling approximation.', 'A room with no ceiling board should calculate walls separately rather than accepting the built-in ceiling area.', 'Very tall walls may favor longer sheets, but lifting, transport, and local handling requirements still matter.'],
    interpretation: ['The answer is a whole-sheet ordering baseline, not a cutting diagram.', 'Compare net drywall area with the room geometry to catch a misplaced decimal or omitted opening.', 'A higher waste percentage reflects difficult cuts and layout, not an instruction to ignore reusable offcuts.', 'Keep specialty board quantities separate when only bathrooms, garages, or rated assemblies require them.'],
    faqs: [
      { question: 'Does the result include the ceiling?', answer: 'Yes. The stated formula adds ceiling area; calculate walls separately if the ceiling will not be boarded.' },
      { question: 'Should windows be subtracted?', answer: 'Subtract openings that truly will not receive drywall, measured by their actual area.' },
      { question: 'Does it include both sides of a partition?', answer: 'No. Each surface to be boarded must be included in the measurement scope.' },
      { question: 'Why use whole sheets?', answer: 'Sheets are sold as full pieces, so a fractional arithmetic result is rounded upward for purchasing.' },
      { question: 'Does it estimate joint compound?', answer: 'No. Compound, tape, fasteners, and finishing materials depend on joints, finish level, and product instructions.' }
    ],
    relatedLinks: [related('/calculators/construction/square-footage', 'Square Footage Calculator', 'Measure a separate surface.'), related('/calculators/construction/paint', 'Paint Calculator', 'Estimate paint after boarding.'), related('/articles/construction-materials-estimating', 'Construction materials estimating', 'Review measurement and waste planning.')]
  },
  'brick': {
    title: 'Brick Calculator guide',
    introduction: [
      'A brick wall is counted from the repeating face module, not from brick face alone. Mortar joints occupy visible wall area between units, so ignoring them inflates a brick count. This calculator measures the net wall face after openings, divides by the area of one brick plus its joint in both directions, applies a breakage allowance, and rounds upward to whole bricks. It is a useful purchasing estimate for a uniform running field.',
      'Use brick length and height on the exposed wall face, not brick depth. Enter the joint thickness intended for the repeating pattern, along with actual wall length, wall height, and opening area. Confirm the supplier’s stated brick dimensions and coverage because formats vary. The count concerns face units only; it cannot establish wall thickness, bond pattern, structural support, moisture detailing, or mortar volume.'
    ],
    formula: {
      equation: 'Brick module area = (brick length + joint) × (brick height + joint). Bricks = wall area minus openings, divided by module area, then increased for waste.',
      variables: ['wall area = wall length × wall height', 'module area = brick face plus one mortar joint in each direction', 'openings = unbricked wall area', 'waste = breakage allowance percentage']
    },
    examples: [
      { heading: '30 ft by 6 ft wall with standard face brick', body: 'The wall face is 180 ft²; subtracting 24 ft² openings leaves 156 ft². An 8-inch by 2.25-inch brick with a 3/8-inch joint has a 8.375 by 2.625 inch module, or about 0.1527 ft². Net coverage needs about 1,022 bricks. Applying 10% breakage yields about 1,124, which rounds to 1,124 whole bricks.' },
      { heading: 'Metric wall with 20 cm by 6 cm units', body: 'For a 9.14 m by 1.83 m wall with 2.23 m² openings, the net face is about 14.50 m². With 20 cm length, 6 cm height, and 1 cm joints, the module is 0.21 × 0.07 = 0.0147 m². The net count is about 987; a 10% allowance produces 1,086 whole bricks after rounding upward.' }
    ],
    usage: ['Measure the visible wall length and height for one consistent face or wythe.', 'Measure all door, window, and permanent opening areas that will not receive brick.', 'Enter actual brick face length and height plus the planned mortar joint thickness.', 'Apply a breakage allowance suited to cuts, handling, corners, pattern, and reserve stock.', 'Round upward and separately list special shapes, lintels, ties, flashing, mortar, and reinforcement.'],
    unitGuidance: ['Imperial walls use feet and openings use square feet, while brick faces and joints use inches. Metric walls use metres and brick faces and joints use centimetres.', 'The module calculation requires compatible length units before multiplication; the calculator performs the conversion in its selected system.', 'Brick depth is deliberately absent because this is a face-count formula, not a volume or wall-thickness calculation.'],
    assumptions: ['The wall face is flat and rectangular before openings are removed.', 'A single brick format and uniform joint are used throughout the calculated field.', 'The stated joint is represented once in length and once in height for each repeating module.', 'Waste is added to the net module count after openings are excluded.'],
    limitations: ['It does not calculate mortar volume, wall ties, cavity components, structural adequacy, or foundation design.', 'Arches, soldier courses, quoin details, corners, and bond patterns can change cuts and unit counts.', 'Supplier blends, batch variation, minimum order quantities, and site breakage may affect the final order.'],
    mistakes: ['Using brick depth instead of face height or face length gives an unrelated module.', 'Leaving out the mortar joint makes each module too small and overstates brick quantity.', 'Subtracting window dimensions as a length rather than their area is incorrect.', 'Rounding down after a breakage allowance defeats the purpose of ordering whole units.'],
    edgeCases: ['For a wall with net area of zero or less, verify that openings have not been entered for the wrong scope.', 'A joint-free dry-stack system needs its actual manufacturer module, not an assumed mortar joint.', 'Half bricks at ends and corners may be cut from full units or sold as specials; treat them in the waste and detail takeoff.', 'Multiple brick formats should be calculated in separate fields because one average module is not meaningful.'],
    interpretation: ['The result is the quantity of face bricks to obtain for the defined uniform wall field.', 'A large difference from a supplier coverage chart is a reason to compare joint assumptions and brick dimensions.', 'The allowance is a risk buffer for breakage and cuts, not a measure of mortar or structural material.', 'Document the bond, face size, and joint with the estimate so a later revision can be traced.'],
    faqs: [
      { question: 'Why is the mortar joint added?', answer: 'A repeating wall module includes the brick face and the space occupied by its mortar joint.' },
      { question: 'Does this calculate mortar?', answer: 'No. Mortar volume depends on depth, wall thickness, joint profile, mix, and workmanship.' },
      { question: 'Should openings be removed?', answer: 'Yes, enter the actual face area that will not receive brick, while taking lintels and reveals separately.' },
      { question: 'What does breakage allowance cover?', answer: 'It allows for handling damage, cuts, pattern adjustments, and a practical reserve; choose it for the project.' },
      { question: 'Can I use it for veneer?', answer: 'It can estimate a uniform veneer face count, but drainage, ties, backing, and code details require separate design.' }
    ],
    relatedLinks: [related('/calculators/construction/drywall', 'Drywall Calculator', 'Estimate interior board sheets.'), related('/calculators/construction/square-footage', 'Square Footage Calculator', 'Calculate surface area.'), related('/articles/construction-materials-estimating', 'Construction materials estimating', 'Understand material allowances.')]
  },
  gravel: {
    title: 'Gravel Calculator guide',
    introduction: [
      'Gravel is commonly quoted by cubic yard, cubic metre, ton, or tonne, so an estimate must keep volume and weight distinct. This calculator first finds the rectangular volume at finished depth, increases it for waste and settlement, then uses the supplied bulk density to estimate weight and an optional price to estimate material cost. It gives a clear bridge between a landscape measurement and the unit a quarry or landscape yard may sell.',
      'Measure the covered length and width, then enter the compacted finished depth specified for the layer. Base rock, bedding aggregate, and decorative stone should be estimated separately because their depths, densities, and prices can differ. Use the supplier’s density whenever possible: stone size, gradation, moisture, and compaction make a generic density only an approximation. Delivery charges, minimum loads, and installation are outside the modeled material cost.'
    ],
    formula: {
      equation: 'Adjusted volume = length × width × depth × (1 + waste ÷ 100). Weight = volume × bulk density; cost = tonnes × price.',
      variables: ['length × width × depth = rectangular volume', 'waste = waste and settlement percentage', 'bulk density = tons per cubic yard or kilograms per cubic metre', 'price = cost per ton or tonne']
    },
    examples: [
      { heading: '20 ft by 10 ft path at 3 inches', body: 'Convert 3 inches to 0.25 ft. The base volume is 20 × 10 × 0.25 ÷ 27, or about 1.85 yd³. With 10% waste and settlement, adjusted volume is about 2.04 yd³. At 1.4 tons per yd³, estimated weight is about 2.85 tons. A $55-per-ton material price produces an estimate near $157 before delivery and tax.' },
      { heading: 'Metric driveway layer', body: 'A 6 m by 3 m area at 75 mm finished depth has 1.35 m³ before allowance. At 8% it becomes 1.458 m³. Using supplier density of 1,680 kg/m³ yields about 2,449 kg, or 2.45 tonnes. At 55 per tonne, the modeled material cost is about 135 in the entered currency denomination.' }
    ],
    usage: ['Split the project into rectangles and calculate every layer with its own depth and material specification.', 'Enter length, width, and compacted finished depth rather than a loose depth guessed from a pile.', 'Use current supplier density and price in the unit the supplier quotes.', 'Apply waste and settlement once through the provided percentage, then compare both adjusted volume and weight with ordering increments.', 'Ask the supplier about delivery capacity, minimum quantities, moisture basis, and whether the material is sold loose or compacted.'],
    unitGuidance: ['Imperial dimensions use feet for length and width and inches for depth; results include cubic yards and tons when imperial inputs and density are selected.', 'Metric dimensions use metres and centimetres, with density in kilograms per cubic metre and weight in tonnes.', 'A cubic yard measures space and a ton measures mass. They cannot be converted without a material-specific bulk density.', 'Price follows the selected weight unit, so do not apply a per-ton quote to a tonne result without converting or selecting the matching unit.'],
    assumptions: ['The placed area is rectangular with a uniform finished depth.', 'The entered density represents the same material and condition being ordered.', 'Waste and settlement apply as a percentage increase to base volume.', 'The optional price is a material-only rate per modeled ton or tonne.'],
    limitations: ['It does not model tapered grades, crown, drainage swales, excavation, geotextile, edging, compaction equipment, or delivery fees.', 'Loose and compacted volumes can differ, and quarry density can change with moisture and gradation.', 'The calculation is not a specification for pavement base thickness or a substitute for drainage and geotechnical design.'],
    mistakes: ['Entering loose pile depth when the project calls for compacted depth can underorder material.', 'Assuming every gravel product weighs 1.4 tons per cubic yard ignores product and moisture variation.', 'Confusing cubic yards with square yards omits depth entirely.', 'Multiplying price by volume when the quoted price is per ton or tonne produces the wrong cost basis.'],
    edgeCases: ['A circular drive, tapered trench, or irregular bed should be divided into appropriate geometric areas before depth is applied.', 'If the supplier sells only whole half-yard or full-ton increments, round according to that increment after reviewing access and storage.', 'A zero price can still yield a valid volume and weight estimate, but it does not represent a free delivered project.', 'Very shallow decorative layers may be strongly affected by existing grade variation and raking losses.'],
    interpretation: ['Read adjusted volume as the space to fill and weight as the density-based ordering cross-check.', 'When volume and weight produce different supplier recommendations, confirm the supplier’s own density and sales unit rather than averaging them.', 'The cost is a transparent material estimate only; add delivery, taxes, and installation separately.', 'Retain the quoted density beside the result, because changing it changes weight and cost without changing physical volume.'],
    faqs: [
      { question: 'Why does gravel have both volume and weight?', answer: 'Volume describes the space to fill; density converts that space to the weight many suppliers load and sell.' },
      { question: 'Should I use compacted depth?', answer: 'Yes. Start with the required finished compacted depth and use the allowance for settlement or placement losses.' },
      { question: 'Does the cost include delivery?', answer: 'No. The formula multiplies modeled tonnes by entered material price only.' },
      { question: 'Can one density be used for all stone?', answer: 'No. Use the quarry or supplier figure for the exact aggregate, moisture condition, and sales basis.' },
      { question: 'How do I handle multiple layers?', answer: 'Calculate base, bedding, and topstone separately because each can have a different depth, density, and price.' }
    ],
    relatedLinks: [related('/calculators/construction/cubic-yard', 'Cubic Yard Calculator', 'Convert rectangular dimensions to bulk volume.'), related('/calculators/construction/mulch', 'Mulch Calculator', 'Estimate landscape bed material.'), related('/articles/construction-materials-estimating', 'Construction materials estimating', 'Measure and order bulk materials.')]
  }
};