import type { PhaseFourSlug } from './phase-four-routes';
import { findShoeSizeMatch, formatShoeSize, shoeGroupLabels, type ShoeGroup, type ShoeRegion } from './shoe-size';
export type { PhaseFourSlug } from './phase-four-routes';
export type Field = { key: string; label: string; value: string; type: 'number' | 'select' | 'text'; min?: number; max?: number; step?: string; options?: readonly { value: string; label: string }[] };
export type Result = { primary: string; summary: string; details: readonly { label: string; value: string }[]; error?: string };
export type Definition = { slug: PhaseFourSlug; name: string; description: string; category: 'Automotive & EV' | 'Converters' | 'Money & Finance' | 'Salary & Work' | 'Business'; categorySlug: 'automotive' | 'converters' | 'finance' | 'salary-work' | 'business'; href: string; seoTitle: string; seoDescription: string; h1: string; aliases: readonly string[]; tags: readonly string[]; fields: readonly Field[]; resultLabel: string; formula: string; variables: string; safetyNotice: string; limitations: string; educationalSections: readonly { heading: string; body: string }[]; faqs: readonly { question: string; answer: string }[]; sourceLinks: readonly { label: string; href: string }[]; relatedRoutes: readonly string[] };
const n=(key:string,label:string,value:string,min=0,max=1e9):Field=>({key,label,value,type:'number',min,max,step:'any'});
const s=(key:string,label:string,value:string,options:readonly [string,string][]):Field=>({key,label,value,type:'select',options:options.map(([value,label])=>({value,label}))});
const money=(x:number)=>`$${x.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const valid=(v:string[], fields:readonly Field[])=>v.length===fields.length&&v.every((x,i)=>fields[i].type==='select'
 ? Boolean(fields[i].options?.some((option)=>option.value===x))
 : (x.trim()!==''&&Number.isFinite(Number(x))&&Number(x)>= (fields[i].min??-Infinity)&&Number(x)<= (fields[i].max??Infinity)));
const aliasesBySlug: Record<PhaseFourSlug, readonly string[]> = {
 mileage:['trip MPG','fuel mileage'], 'roman-numeral':['roman numerals','arabic number conversion'], 'shoe-size':['shoe conversion','baby shoe size','kids shoe size','women shoe size','men shoe size','US UK EU shoe size'],
 'social-security':['SSA retirement benefit','retirement claiming age'], 'take-home-pay':['net pay','gross to net'], 'tire-size':['speedometer difference','tire circumference'],
 '401k':['retirement plan','employer match'], annuity:['annuity payout','income annuity'], apr:['annual percentage rate','loan fees'],
 'auto-lease':['vehicle lease','money factor'], bond:['coupon bond','bond price'], budget:['monthly spending','income and expenses'],
 commission:['sales commission','commission rate'], 'credit-card':['credit card payoff','card interest'], 'debt-consolidation':['debt payoff','consolidation loan'],
};
const phaseFourContexts: Partial<Record<PhaseFourSlug, string>> = {
 mileage:'Mileage is distance divided by fuel actually used over the same refill-to-refill interval. Odometer error, partial fills, idling, towing, weather, speed, and route conditions are outside this trip calculation.',
 'roman-numeral':'Conventional modern Roman notation uses I, V, X, L, C, D, and M with limited subtractive pairs such as IV, IX, XL, XC, CD, and CM. This converter deliberately accepts only whole numbers from 1 through 3,999 and does not attempt medieval variants, overbar notation, zero, negatives, fractions, dates, or text parsing.',
 'social-security':'The estimate multiplies a primary insurance amount supplied by the user by a simplified claiming-age factor. It does not calculate PIA from an earnings record or decide eligibility, full retirement age, spousal or survivor benefits, work deductions, taxation, cost-of-living adjustments, disability rules, windfall provisions, or an official award.',
 'take-home-pay':'Net pay here subtracts one entered tax percentage and one pay-period deduction from gross pay. It does not reconstruct withholding tables, benefit elections, overtime rules, wage garnishments, filing status, or jurisdiction.',
 commission:'Commission applies only to eligible sales at the entered percentage, then adds the entered base pay. It does not model tiers, quotas, draws, returns, chargebacks, split credit, caps, accelerators, or payroll withholding.',
 'shoe-size':'The dedicated converter uses separate Baby / toddler, Children / youth, Women, and Men reference tables for US, UK, and EU labels and reports approximate foot length. A brand’s last, width, materials, socks, foot shape, orthotics, and intended activity can alter fit even where the nominal label agrees.',
 'tire-size':'The sidewall calculation converts section width and aspect ratio into two sidewall heights, adds the rim diameter, and derives circumference and revolutions from the resulting diameter. Real mounted diameter, tread wear, pressure, load, wheel width, manufacturer tolerances, clearance, gearing, ABS calibration, and approved fitment can differ.',
 '401k':'The projection compounds the current balance and adds separate employee and employer annual contributions at year end. It does not enforce plan eligibility, vesting, payroll timing, catch-up categories, changing IRS limits, investment fees, taxes, loans, withdrawals, inflation, asset volatility, or the sequence in which returns occur.',
 annuity:'This annuity model converts the entered annual rate to a periodic rate and solves for a level payout that exhausts the starting value over the selected term. It does not quote an insurer or include mortality credits, guarantees, riders, surrender terms, commissions, taxes, inflation protection, market-linked adjustments, or counterparty risk.',
 apr:'The APR solver treats fees as withheld from proceeds, then finds the monthly rate whose fixed payments equal the net cash received. It is not a regulatory disclosure calculation for every jurisdiction and does not model irregular payment dates, optional products, compounding conventions, changing rates, late charges, prepayment, or taxes.',
 'auto-lease':'The lease estimate divides depreciation across the term and adds a finance charge based on capitalized cost, residual value, and money factor. It excludes sales tax method, acquisition and disposition fees, registration, incentives, trade equity, mileage limits, excess wear, security deposits, capitalization reductions, and dealer-specific rounding.',
 bond:'The bond price is the present value of annual coupons plus face value discounted at one annual yield through maturity. It assumes scheduled payments and does not include accrued interest, settlement date, day-count conventions, semiannual coupons, calls, puts, default probability, reinvestment, taxes, inflation, transaction costs, or market liquidity.',
 budget:'The budget result subtracts entered recurring monthly expenses from entered monthly after-tax income. It does not discover missing transactions or distinguish essential, discretionary, annual, seasonal, debt-principal, savings, and emergency items; convert irregular amounts to a consistent monthly basis before interpreting the surplus or shortfall.',
 'credit-card':'The payoff estimate assumes one starting balance, a constant APR, no new purchases or fees, and the same payment every month. Issuer daily-balance methods, promotional rates, minimum-payment formulas, compounding dates, late charges, payment timing, transfers, and variable rates can materially change payoff time and interest.',
 'debt-consolidation':'The comparison models the current debt as one constant-rate payoff and contrasts it with one new fixed-rate installment loan including entered fees. Multiple account APRs, minimum payments, promotional expiries, continued card use, closing accounts, credit effects, collateral, taxes, lender qualification, and behavior after consolidation are not predicted.',
};
const expandedEducation=(slug:PhaseFourSlug,name:string,formula:string,fields:readonly Field[],guidance:string,category:Definition['category'])=>{
 const inputs=fields.map(field=>field.label.toLowerCase()).join(', ');
 const context=phaseFourContexts[slug]??'';
 const financial=category==='Money & Finance'||category==='Salary & Work'||category==='Business'
   ? ' Financial and pay figures are planning estimates only. Confirm current terms, taxes, eligibility, payroll rules, fees, and contract documents before making a decision.'
   : '';
 const shoe=slug==='shoe-size'
   ? ' Shoe labels are not a fit guarantee: a brand’s last, width, materials, socks, and intended use can change fit even when the regional size label matches.'
   : '';
 return [
  {heading:'Choose inputs that match',body:`Enter ${inputs} for one consistent situation. ${context} Confirm the time period, unit, and definition of every number before comparing results. Keep the original source values so the result can be revisited when the assumptions change.`},
  {heading:'How to check the calculation',body:`FigureNest applies ${formula}. ${context} To check the answer, write the inputs with their units, follow the operation in the same order, and make a rough magnitude check before relying on displayed rounding. ${guidance}`},
  {heading:'Interpret the estimate',body:`Treat the ${name} output as an answer to this focused method: ${formula}. ${context} Compare two scenarios only when the ${inputs} use the same basis and change one input at a time.${financial}${shoe}`},
  {heading:'Limits and common mistakes',body:`For ${name}, check each of these source entries before trusting the result: ${inputs}. ${context} Common mistakes include entering a percentage in the wrong form, mixing monthly and annual values, rounding before the final step, and assuming a general formula includes a local rule or provider policy.`},
  {heading:'Useful next step',body:`Save the ${name} inputs, result, and date used for an important comparison. ${context} Recalculate this ${formula} method after a relevant source value changes. Related calculators may answer the next question with different boundaries and assumptions.`},
 ];
};
const make=(slug:PhaseFourSlug,name:string,category:Definition['category'],categorySlug:Definition['categorySlug'],href:string,fields:readonly Field[],formula:string,description:string,seoDescription:string,guidance:string,sourceLinks:readonly {label:string;href:string}[]=[],relatedRoutes:readonly string[]=[]):Definition=>{
  const specific=`${guidance} This calculator is an arithmetic estimate, not a quote, contract, fit guarantee, tax return, benefit determination, route service, or recommendation. Current terms, product specifications, rules, and personal circumstances can change the real outcome.`;
  return {slug,name,category,categorySlug,href,fields,formula,description,h1:name,seoTitle:`${name} | FigureNest`,seoDescription,aliases:aliasesBySlug[slug],tags:[slug.replaceAll('-',' '),name.toLowerCase(),category.toLowerCase(),...aliasesBySlug[slug]],resultLabel:'RESULT',variables:'Enter values in the units named in each field. The calculator retains precision during the calculation and rounds displayed currency and measurements for readability.',safetyNotice:slug==='401k'?'The $24,500 employee elective-deferral limit is a 2026 planning assumption, not a current-limit determination. Verify the current IRS limit, your plan rules, and catch-up eligibility before contributing.':'Before relying on an estimate, check the current documents, labels, and terms that apply to your situation.',limitations:specific,sourceLinks,relatedRoutes,educationalSections:[
   {heading:'What this calculation uses',body:`${formula}. ${guidance}`},
   ...expandedEducation(slug,name,formula,fields,guidance,category),
  ],faqs:[
  {question:`What does this ${name.toLowerCase()} include?`,answer:`It uses the displayed inputs and the stated formula. ${guidance}`},
   {question:`Why might another ${name.toLowerCase()} result differ?`,answer:`Another result may use a different method or input scope. This calculator uses ${formula}.`},
 {question:'Does FigureNest send my inputs anywhere?',answer:'No. The calculation runs locally in the browser and does not use a calculation service.'},
 ]};
};
export const phaseFourDefinitions:Record<PhaseFourSlug,Definition>={
  mileage:make('mileage','Mileage Calculator','Automotive & EV','automotive','/calculators/automotive/mileage',[n('distance','Trip distance (miles)','120',0.1,100000),n('fuel','Fuel used (gallons)','4',0.01,10000)],'MPG = user-entered trip distance ÷ fuel used','Calculate fuel economy from a trip distance you enter yourself and fuel consumed; this page does not route, map, or geocode travel.','Calculate trip MPG from miles traveled and gallons of fuel used, with a clear result based only on your entries.','Use fuel purchased for the same trip as the distance you enter.',[{label:'U.S. Department of Energy — Fuel economy',href:'https://www.fueleconomy.gov/'}],['/calculators/automotive/fuel-cost','/calculators/automotive/fuel-economy','/converters/length']),
  'roman-numeral':make('roman-numeral','Roman Numeral Converter','Converters','converters','/converters/roman-numeral',[n('number','Whole number (1–3999)','2026',1,3999)],'Roman numeral uses standard subtractive notation','Convert a whole number from 1 through 3,999 to conventional Roman-numeral notation.','Convert whole numbers from 1 to 3,999 into standard Roman numerals using conventional subtractive notation.','Roman numerals have no decimal or zero notation in this converter.',[{label:'Encyclopaedia Britannica — Roman numerals',href:'https://www.britannica.com/science/Roman-numeral'}],['/converters/unit','/converters/length']),
  'shoe-size':make('shoe-size','Shoe Size Converter','Converters','converters','/converters/shoe-size',[s('group','Wearer group','men',[['baby','Baby / toddler'],['kids','Children / youth'],['women','Women'],['men','Men']]),s('region','Input sizing system','EU',[['US','US'],['UK','UK'],['EU','EU']]),n('size','Shoe size','42.5',0,60)],'Age-group-specific US, UK, and EU shoe-size reference tables','Compare approximate US, UK, and EU shoe sizes for babies and toddlers, children and youth, women, and men, with foot-length references and brand-fit caveats.','Convert approximate US, UK, and EU shoe sizes for babies, children, women, and men with age-group tables, foot-length references, and fit caveats.','Choose the wearer group first, then use this as a starting point and check the brand’s own size chart and measured foot length.',[{label:'ISO 9407 footwear sizing overview',href:'https://www.iso.org/standard/61484.html'}],['/converters/length','/converters/unit']),
  'social-security':make('social-security','Social Security Benefit Estimator','Money & Finance','finance','/calculators/finance/social-security',[n('pia','Your estimated PIA (monthly USD)','2000',0,20000),n('claimAge','Claiming age (62–70)','67',62,70)],'Estimated monthly benefit = user-entered PIA × claiming-age factor','US-only approximate estimator using your entered primary insurance amount (PIA) and published claiming-age adjustment factors; assumptions dated 2026.','Estimate a monthly Social Security retirement benefit from your PIA and selected claiming age using stated factors.','Your PIA should come from your own Social Security record; this does not determine eligibility.',[{label:'Social Security Administration — Retirement benefits',href:'https://www.ssa.gov/benefits/retirement/'}],['/calculators/finance/401k','/calculators/finance/annuity','/calculators/salary-work/take-home-pay']),
  'take-home-pay':make('take-home-pay','Take-Home Pay Calculator','Salary & Work','salary-work','/calculators/salary-work/take-home-pay',[n('gross','Gross pay per pay period (USD)','2500',0,1e7),n('tax','User-entered tax rate (%)','22',0,100),n('deductions','User-entered deductions (USD)','100',0,1e7)],'Net pay = gross pay − gross pay × entered tax rate − entered deductions','Estimate pay after only the tax rate and deductions you enter; no tax tables, filing status, or jurisdiction assumptions are used.','Calculate estimated take-home pay from gross pay, your tax-rate assumption, and deductions for one pay period.','Enter a rate and deductions that match the same pay period as gross pay.',[{label:'IRS — Tax withholding',href:'https://www.irs.gov/payments/tax-withholding'}],['/calculators/salary-work/salary','/calculators/salary-work/overtime','/calculators/finance/budget']),
  'tire-size':make('tire-size','Tire Size Calculator','Automotive & EV','automotive','/calculators/automotive/tire-size',[n('width','Section width (mm)','225',100,500),n('aspect','Aspect ratio (%)','45',20,100),n('rim','Rim diameter (in)','17',10,30),n('reference','Reference tire diameter (in)','25',10,50)],'diameter = rim + 2 × width × aspect ÷ 25.4 ÷ 100','Calculate tire diameter, circumference, revolutions per mile, and speedometer delta from sidewall dimensions.','Calculate tire diameter, circumference, revolutions per mile, and an estimated speedometer difference from sidewall sizes.','Use the full sidewall marking and compare the calculated diameter with the vehicle’s approved sizes.',[{label:'NHTSA — Tires',href:'https://www.nhtsa.gov/vehicle-safety/tires'}],['/calculators/automotive/fuel-economy','/converters/speed','/converters/length']),
  '401k':make('401k','401(k) Growth Calculator','Money & Finance','finance','/calculators/finance/401k',[n('balance','Current balance (USD)','25000',0,10000000),n('employee','Employee contribution per year (USD)','10000',0,1000000),n('employer','Employer contribution per year (USD)','3000',0,1000000),n('rate','Annual return after fees (%)','6',-50,50),n('years','Years','20',1,60)],'Future value = current balance compounded annually plus yearly employee and employer deposits compounded at the entered net rate','US-only 401(k) estimate using a current balance and separate employee/employer annual amounts. The 2026 employee elective-deferral planning limit is stated as $24,500; verify IRS limits and catch-up eligibility.','Project a 401(k) balance from a current balance, annual employee and employer contributions, return, and years.','Contributions are modeled at year end; use a return assumption after investment fees.',[{label:'IRS — 401(k) plans',href:'https://www.irs.gov/retirement-plans/401k-plans'}],['/calculators/finance/annuity','/calculators/finance/compound-interest','/calculators/finance/savings']),
  annuity:make('annuity','Annuity Calculator','Money & Finance','finance','/calculators/finance/annuity',[n('principal','Starting value (USD)','100000',0,1e8),n('rate','Annual rate (%)','5',-50,50),n('years','Years','20',1,100),s('mode','Payout mode','monthly',[['monthly','Monthly payout'],['annual','Annual payout']])],'Level payout amortizes starting value over the selected term at the entered annual rate','Estimate a level payout from a stated starting value, rate, term, and selected monthly or annual payout mode.','Estimate a level monthly or annual payout by amortizing a starting value over your selected term and rate.','This is a level-payment math model, not an annuity product quote or illustration.',[{label:'SEC Investor.gov — Annuities',href:'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/variable'}],['/calculators/finance/401k','/calculators/finance/compound-interest','/calculators/finance/savings']),
  apr:make('apr','APR Calculator','Money & Finance','finance','/calculators/finance/apr',[n('amount','Loan amount before withheld fees (USD)','10000',1,1e8),n('fees','Fees withheld from proceeds (USD)','200',0,1e7),n('received','Cash received by borrower (USD)','9800',0.01,1e8),n('payment','Monthly payment (USD)','220',0.01,1e7),n('months','Number of monthly payments','60',1,600)],'APR is the annualized monthly rate solved from cash received, fixed payment, and term; cash received equals loan amount minus withheld fees','Estimate APR from the cash a borrower receives, fixed monthly payments, and term after fees withheld from loan proceeds.','Calculate the annualized rate implied by net cash received, a fixed payment, and the number of monthly payments.','Fees are treated as withheld from proceeds, so cash received must equal loan amount minus those fees.',[{label:'Consumer Financial Protection Bureau — Annual percentage rate',href:'https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733/'}],['/calculators/finance/loan','/calculators/finance/interest-rate','/calculators/finance/credit-card']),
  'auto-lease':make('auto-lease','Auto Lease Calculator','Money & Finance','finance','/calculators/finance/auto-lease',[n('cap','Capitalized cost (USD)','35000',0,1e7),n('residual','Residual value (USD)','22000',0,1e7),n('months','Lease term (months)','36',1,84),n('money','Money factor','0.0025',0,0.1)],'Monthly base payment = depreciation charge + finance charge','Estimate a pre-tax lease payment using capitalized cost, residual value, term, and money factor; taxes, acquisition fees, and mileage charges are excluded.','Estimate a pre-tax base lease payment from capitalized cost, residual value, lease term, and money factor.','Taxes, acquisition charges, mileage charges, and lease-end terms are outside this base-payment estimate.',[{label:'Federal Trade Commission — Vehicle leasing',href:'https://consumer.ftc.gov/articles/vehicle-leasing'}],['/calculators/finance/auto-loan','/calculators/automotive/fuel-cost','/calculators/finance/loan']),
  bond:make('bond','Bond Calculator','Money & Finance','finance','/calculators/finance/bond',[n('face','Face value (USD)','1000',1,1e8),n('coupon','Annual coupon rate (%)','5',0,100),n('yield','Annual yield (%)','4',-50,100),n('years','Years to maturity','10',0.1,100)],'Price is the present value of annual coupons plus face value at maturity','Estimate a plain fixed-rate bond price with annual coupons and annual compounding; it does not model accrued interest, taxes, calls, credit risk, or market liquidity.','Estimate the price of a plain annual-coupon bond from face value, coupon rate, yield, and whole years to maturity.','This model assumes annual coupon periods and excludes accrued interest, calls, taxes, and credit risk.',[{label:'U.S. Treasury — Understanding bonds',href:'https://treasurydirect.gov/marketable-securities/understanding-pricing/'}],['/calculators/finance/compound-interest','/calculators/finance/savings','/calculators/finance/simple-interest']),
  budget:make('budget','Budget Calculator','Money & Finance','finance','/calculators/finance/budget',[n('income','Monthly after-tax income (USD)','5000',0,1e7),n('expenses','Monthly expenses (USD)','3800',0,1e7)],'Monthly surplus = income − expenses','Compare user-entered monthly after-tax income and expenses to show a surplus or shortfall.','Compare monthly after-tax income with monthly expenses to calculate a simple surplus or shortfall.','Include only recurring amounts for the same month when making this comparison.',[],['/calculators/salary-work/take-home-pay','/calculators/finance/savings','/calculators/finance/debt-consolidation']),
  commission:make('commission','Commission Calculator','Business','business','/calculators/business/commission',[n('sales','Eligible sales (USD)','10000',0,1e9),n('rate','Commission rate (%)','8',0,100),n('base','Base pay (USD)','0',0,1e9)],'Total pay = base pay + eligible sales × commission rate','Calculate commission and total pay from eligible sales, a user-entered rate, and optional base pay.','Calculate commission and total pay from eligible sales, a commission percentage, and optional base pay.','Confirm which sales qualify and whether the plan applies caps, tiers, draws, or clawbacks.',[],['/calculators/salary-work/salary','/calculators/business/profit-margin','/calculators/business/break-even']),
  'credit-card':make('credit-card','Credit Card Payoff Calculator','Money & Finance','finance','/calculators/finance/credit-card',[n('balance','Current balance (USD)','5000',0.01,1e8),n('apr','APR (%)','20',0,100),n('payment','Monthly payment (USD)','200',0.01,1e7),s('mode','Calculation mode','payoff',[['payoff','Debt payoff mode'],['interest','First-month interest mode']])],'Monthly interest = balance × APR ÷ 12; payoff iterates monthly payments','Estimate credit-card payoff using a constant payment and APR; this includes an explicit debt payoff mode and does not replace issuer terms.','Estimate first-month interest or payoff time from a card balance, APR, and constant monthly payment.','A card issuer may apply a different daily-balance method, fees, promotions, and payment rules.',[{label:'Consumer Financial Protection Bureau — Credit card interest',href:'https://www.consumerfinance.gov/ask-cfpb/how-is-credit-card-interest-calculated-en-51/'}],['/calculators/finance/debt-consolidation','/calculators/finance/apr','/calculators/finance/loan']),
  'debt-consolidation':make('debt-consolidation','Debt Consolidation Calculator','Money & Finance','finance','/calculators/finance/debt-consolidation',[n('debt','Current total debt (USD)','15000',0.01,1e8),n('oldApr','Current blended APR (%)','22',0,100),n('newApr','Consolidation APR (%)','12',0,100),n('months','New payoff term (months)','48',1,600),s('mode','Calculation mode','payoff',[['payoff','Debt payoff mode'],['payment','Payment comparison mode']]),n('fees','New loan fees (USD)','300',0,1e7),n('currentPayment','Current monthly payment (USD)','500',0.01,1e7)],'Payment = principal × monthly rate ÷ (1 − (1 + monthly rate)^−months)','Compare a current constant-payment payoff against a new fixed-rate consolidation loan including entered fees; changing balances, credit effects, and lender terms remain excluded.','Compare a constant-payment debt payoff with a fixed-rate consolidation loan that includes entered loan fees.','The comparison assumes stable balances and rates and does not predict approval or credit-score effects.',[{label:'Consumer Financial Protection Bureau — Debt consolidation',href:'https://www.consumerfinance.gov/ask-cfpb/what-is-a-debt-consolidation-loan-en-1405/'}],['/calculators/finance/credit-card','/calculators/finance/loan','/calculators/finance/apr']),
};
export const phaseFourSlugs=Object.keys(phaseFourDefinitions) as PhaseFourSlug[];
const err=(message:string):Result=>({primary:'Check the values',summary:message,details:[],error:message});
export function calculatePhaseFour(slug:PhaseFourSlug,v:string[]):Result { const d=phaseFourDefinitions[slug]; if(!valid(v,d.fields)) return err('Enter every value in the displayed valid range.'); const x=v.map(Number), one=(primary:string,summary:string,details:readonly {label:string;value:string}[]=[]):Result=>({primary,summary,details});
 if(slug==='mileage') return one(`${(x[0]/x[1]).toFixed(2)} MPG`,'Based only on your entered trip distance and fuel used.');
 if(slug==='roman-numeral'){if(!Number.isInteger(x[0]))return err('Enter a whole number from 1 through 3999.');let z=x[0], out=''; for(const [a,b] of [[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']] as [number,string][]) while(z>=a){out+=b;z-=a;} return one(out,'Standard Roman numeral notation.');}
 if(slug==='shoe-size'){const group=v[0] as ShoeGroup,region=v[1] as ShoeRegion,match=findShoeSizeMatch(group,region,x[2]);if(!match)return err(`Enter a supported ${shoeGroupLabels[group]} ${region} reference size.`);return one(`${shoeGroupLabels[group]} · EU ${formatShoeSize(match.eu)}`,`Reference-table match for ${region} ${formatShoeSize(x[2])}; brand-specific sizing may differ.`,[{label:'US size',value:formatShoeSize(match.us)},{label:'UK size',value:formatShoeSize(match.uk)},{label:'EU size',value:formatShoeSize(match.eu)},{label:'Approx. foot length',value:`${formatShoeSize(match.cm)} cm`}]);}
 if(slug==='social-security'){const f:{[k:number]:number}={62:.7,63:.75,64:.8,65:.8667,66:.9333,67:1,68:1.08,69:1.16,70:1.24}; if(!Number.isInteger(x[1]))return err('Claiming age must be a whole age from 62 through 70.');return one(money(x[0]*f[x[1]])+'/month','US-only approximate estimate using your entered PIA and 2026-stated claiming-age factors.');}
 if(slug==='take-home-pay'){const net=x[0]*(1-x[1]/100)-x[2];if(net<0)return err('Tax and deductions cannot exceed gross pay in this simplified estimate.');return one(money(net),'Uses only your entered tax rate and deductions.');}
 if(slug==='tire-size'){const dia=x[2]+2*x[0]*x[1]/2540,circ=dia*Math.PI,delta=dia/x[3];return one(`${dia.toFixed(2)} in diameter`,'Calculated tire geometry; verify fitment with vehicle and tire professionals.',[{label:'Circumference',value:`${circ.toFixed(2)} in`},{label:'Revolutions per mile',value:(63360/circ).toFixed(1)},{label:'Speedometer delta',value:`${((delta-1)*100).toFixed(2)}%`},{label:'When speedometer indicates 60 mph',value:`actual ≈ ${(60*delta).toFixed(1)} mph`}]);}
 if(slug==='401k'){const r=x[3]/100, years=x[4], deposits=x[1]+x[2];if(x[1]>24500)return err('For this 2026 planning model, employee annual contributions cannot exceed the stated $24,500 elective-deferral limit.');const fv=x[0]*(1+r)**years+deposits*(r===0?years:((1+r)**years-1)/r);return one(money(fv),'2026 planning assumptions: end-of-year contributions and annual compounding after fees.',[{label:'Current balance',value:money(x[0])},{label:'Employee deposits',value:money(x[1]*years)},{label:'Employer deposits',value:money(x[2]*years)}]);}
 if(slug==='annuity'){const p=v[3]==='monthly'?12:1,r=x[1]/100/p,N=x[2]*p, pay=r===0?x[0]/N:x[0]*r/(1-(1+r)**-N);return one(`${money(pay)} per ${v[3]}`,'Level payout; timing and compounding use the selected frequency.');}
 if(slug==='apr'){const amount=x[0],fees=x[1],received=x[2],pay=x[3],months=x[4],expectedReceived=amount-fees;if(fees>=amount||Math.abs(received-expectedReceived)>0.005)return err('Cash received must equal the loan amount minus fees withheld from the proceeds.');if(pay*months<=received)return err('Total payments must exceed the cash received for this fixed-payment schedule.');let lo=0,hi=1;for(let i=0;i<80;i++){const r=(lo+hi)/2,p=pay*(1-(1+r)**-months)/r;if(p>received)lo=r;else hi=r;}return one(`${(hi*12*100).toFixed(2)}% APR`,'Solved from net cash received, fixed monthly payments, and term.',[{label:'Loan amount',value:money(amount)},{label:'Fees withheld',value:money(fees)},{label:'Cash received',value:money(received)}]);}
 if(slug==='auto-lease')return one(money((x[0]-x[1])/x[2]+(x[0]+x[1])*x[3])+'/month','Pre-tax base payment before fees and mileage charges.');
 if(slug==='bond'){if(!Number.isInteger(x[3]))return err('Use whole years because this plain bond model uses annual coupon periods.');const r=x[2]/100,c=x[0]*x[1]/100,price=Array.from({length:x[3]},(_,i)=>c/(1+r)**(i+1)).reduce((a,b)=>a+b,0)+x[0]/(1+r)**x[3];return one(money(price),'Plain annual-coupon bond estimate.');}
 if(slug==='budget')return one(money(x[0]-x[1]),x[0]>=x[1]?'Monthly surplus.':'Monthly shortfall.');
 if(slug==='commission')return one(money(x[0]*x[1]/100+x[2]),'Total pay including base pay.',[{label:'Commission',value:money(x[0]*x[1]/100)}]);
 const payment=(P:number,r:number,N:number)=>r===0?P/N:P*r/(1-(1+r)**-N);
 if(slug==='debt-consolidation'){const newBalance=x[0]+x[5], newPayment=payment(newBalance,x[2]/1200,x[3]);let balance=x[0], currentMonths=0, oldRate=x[1]/1200;if(x[6]<=balance*oldRate)return err('Current payment must exceed first-month current-debt interest.');while(balance>0&&currentMonths<1200){balance=balance*(1+oldRate)-x[6];currentMonths++;}return one(money(newPayment)+'/month',v[4]==='payoff'?'New-loan payment compared with your entered current payoff payment.':'Payment comparison using entered fees and rates.',[{label:'New loan balance including fees',value:money(newBalance)},{label:'New loan term',value:`${x[3]} months`},{label:'Current payoff at entered payment',value:`${currentMonths} months`}]);}
 let bal=x[0],months=0;const r=x[1]/1200;if(v[3]==='interest')return one(money(bal*r),'First-month interest at the entered APR.');if(x[2]<=bal*r)return err('Monthly payment must exceed first-month interest to pay off the balance.');while(bal>0&&months<1200){bal=bal*(1+r)-x[2];months++;}return one(`${months} months`,'Estimated payoff with a constant payment and APR.');
}
export const phaseFourUsefulWordCount=(d:Definition)=>JSON.stringify(d).replace(/[^\w\s]/g,' ').split(/\s+/).filter(Boolean).length;
